/**
 * Renderer-owned presentation descriptors for built-in plugin surfaces.
 *
 * Runtime ownership, dependencies, commands, services, scope, and lifecycle come exclusively
 * from the Rust plugin catalog. This list only teaches React how those runtime components should
 * be named and where they render.
 */
export const BUILTIN_UI_COMPONENTS = [
  {
    pluginId: "kernel",
    id: "plugin-manager.page",
    name: "Plugin manager",
    description:
      "The required management plane used to recover and re-enable other features.",
    kind: "page",
    slot: "app.page",
    required: true,
  },
  {
    pluginId: "workspace",
    id: "files.surface",
    name: "Files",
    description: "Workspace file tree, viewer, and file browser.",
    kind: "dockSurface",
    slot: "dock.tabs",
  },
  {
    pluginId: "workspace-search",
    id: "search.modal",
    name: "Workspace search",
    description: "Project-wide content search and result opener.",
    kind: "modal",
    slot: "app.dialogs",
  },
  {
    pluginId: "git",
    id: "git.surface",
    name: "Source control",
    description: "Git dock, source-control dialog, and related commands.",
    kind: "dockSurface",
    slot: "dock.tabs",
  },
  {
    pluginId: "terminal",
    id: "terminal.dock",
    name: "Terminal dock",
    description: "Persistent terminal sessions in the side dock.",
    kind: "dockSurface",
    slot: "dock.tabs",
  },
  {
    pluginId: "lsp",
    id: "lsp.runtime",
    name: "Language servers",
    description: "Project language-server discovery and lifecycle.",
    kind: "runtime",
    slot: "project.runtime",
  },
  {
    pluginId: "automation",
    id: "automation.page",
    name: "Automations",
    description: "Scheduled-work page and automation entry points.",
    kind: "page",
    slot: "app.page",
  },
  {
    pluginId: "browser",
    id: "browser.dock",
    name: "Browser dock",
    description: "Authenticated in-app browser surface and its dock opener.",
    kind: "dockSurface",
    slot: "dock.tabs",
  },
  {
    pluginId: "canvas",
    id: "canvas.editor",
    name: "Canvas editor",
    description:
      "Structured visual canvas blocks. Component policy is separate from the Canvas safety feature gate; enabling this component does not open the production gate.",
    kind: "editorBlock",
    slot: "editor.blocks",
  },
  {
    pluginId: "issues",
    id: "issues.modal",
    name: "Issues",
    description: "GitHub and Linear issue browser and delegation flow.",
    kind: "modal",
    slot: "app.dialogs",
  },
  {
    pluginId: "memory",
    id: "memory.settings",
    name: "Memory",
    description: "Memory policy controls and receipt surfaces.",
    kind: "settingsSection",
    slot: "settings.sections",
  },
  {
    pluginId: "device-sync",
    id: "device-sync.settings",
    name: "Device sync",
    description: "Device-sync methods, status, and data-scope controls.",
    kind: "settingsSection",
    slot: "settings.sections",
  },
  {
    pluginId: "remote",
    id: "remote.modal",
    name: "Remote control",
    description: "Remote-device pairing and connection management.",
    kind: "modal",
    slot: "app.dialogs",
  },
  {
    pluginId: "scenes",
    id: "scenes.surface",
    name: "Agent scenes",
    description: "Scene picker, studio, banners, and pipeline controls.",
    kind: "sessionSurface",
    slot: "session.chrome",
  },
  {
    pluginId: "usage",
    id: "usage.settings",
    name: "Usage",
    description: "Provider quota and usage settings surfaces.",
    kind: "settingsSection",
    slot: "settings.sections",
  },
  {
    pluginId: "voice",
    id: "voice.composer",
    name: "Voice input",
    description: "Composer dictation and structured voice input.",
    kind: "composerAction",
    slot: "composer.actions",
  },
] as const;
