import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

// Typed bridge to the Rust core. In a later pass this is generated by tauri-specta; hand-written now.

export interface ProviderInfo {
  id: string;
  display_name: string;
  available: boolean;
  needs_node: boolean;
}

export interface SkillInfo {
  id: string;
  name: string;
  description: string;
  icon: string | null;
  kind: string;
}

export interface SessionInfo {
  id: string;
  title: string;
  provider: string | { custom: string };
  model: string | null;
  cwd: string;
  worktree_path: string | null;
  permission_mode: string;
  acp_session_id: string | null;
  created_at: number;
}

/// Neutral document shape the editor serializes into; matches core `DocBlock` serde.
export type DocBlock =
  | { type: "text"; text: string }
  | { type: "skill"; skill_id: string; params: Record<string, string> }
  | { type: "file"; path: string };

/// Mirrors core `Event` (tagged by `event`, snake_case).
export type CoreEvent =
  | { event: "session_created"; session: string }
  | { event: "agent_text"; session: string; message_id: string; text: string }
  | { event: "agent_thought"; session: string; text: string }
  | { event: "tool_call"; session: string; id: string; title: string; status: string }
  | { event: "plan"; session: string; entries: string[] }
  | { event: "permission_request"; session: string; request_id: string; title: string; options: [string, string][] }
  | { event: "usage"; session: string; input_tokens: number; output_tokens: number }
  | { event: "turn_ended"; session: string; stop_reason: string }
  | { event: "error"; session: string | null; message: string };

export interface PtyOutput {
  id: number;
  data: string;
}

/// Mirrors core `Part` (tagged by `kind`).
export type Part =
  | { kind: "text"; text: string }
  | { kind: "reasoning"; text: string }
  | { kind: "tool_call"; id: string; title: string; status: string }
  | { kind: "plan"; entries: string[] };

export type TranscriptEntry = [string, Part]; // [role, part]

export type SkillPayload =
  | { kind: "fragment"; text: string }
  | { kind: "macro"; template: string; slots: string[] };

export interface Skill {
  id: string;
  name: string;
  description: string;
  icon: string | null;
  payload: SkillPayload;
}

// True only inside the Tauri webview; lets `vite build`/`preview` run in a plain browser.
const inTauri = typeof (globalThis as { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__ !== "undefined";

const FALLBACK_PROVIDERS: ProviderInfo[] = [
  { id: "claude_code", display_name: "Claude Code", available: false, needs_node: true },
  { id: "codex", display_name: "OpenAI Codex", available: false, needs_node: true },
  { id: "grok", display_name: "Grok", available: false, needs_node: false },
  { id: "cursor", display_name: "Cursor", available: false, needs_node: false },
  { id: "opencode", display_name: "OpenCode", available: false, needs_node: false },
];

const FALLBACK_SKILLS: SkillInfo[] = [
  { id: "reviewer", name: "Code Reviewer", description: "Meticulous reviewer", icon: "🔍", kind: "fragment" },
  { id: "test-writer", name: "Test Writer", description: "Thorough tests", icon: "🧪", kind: "fragment" },
  { id: "security-audit", name: "Security Audit", description: "Find vulns", icon: "🛡️", kind: "fragment" },
  { id: "commit-macro", name: "Commit Message", description: "Commit macro", icon: "📝", kind: "macro" },
];

export async function listProviders(): Promise<ProviderInfo[]> {
  return inTauri ? invoke<ProviderInfo[]>("list_providers") : FALLBACK_PROVIDERS;
}

export async function listSkills(): Promise<SkillInfo[]> {
  return inTauri ? invoke<SkillInfo[]>("list_skills") : FALLBACK_SKILLS;
}

export async function listSessions(): Promise<SessionInfo[]> {
  return inTauri ? invoke<SessionInfo[]>("list_sessions") : [];
}

export async function newSession(provider: string, cwd: string, useWorktree: boolean): Promise<void> {
  if (inTauri) await invoke("new_session", { provider, cwd, useWorktree });
}

export async function submitPrompt(session: string, doc: DocBlock[]): Promise<void> {
  if (inTauri) await invoke("submit_prompt", { session, doc });
}

export async function answerPermission(session: string, requestId: string, optionId: string | null): Promise<void> {
  if (inTauri) await invoke("answer_permission", { session, requestId, optionId });
}

export async function setPermissionMode(session: string, mode: string): Promise<void> {
  if (inTauri) await invoke("set_permission_mode", { session, mode });
}

export async function cancelTurn(session: string): Promise<void> {
  if (inTauri) await invoke("cancel_turn", { session });
}

export async function ptySpawn(
  id: number,
  cwd: string | null,
  rows: number,
  cols: number,
  tmuxSession?: string | null,
): Promise<void> {
  if (inTauri) await invoke("pty_spawn", { id, cwd, rows, cols, tmuxSession: tmuxSession ?? null });
}

export async function tmuxAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("tmux_available") : false;
}

export async function ptyWrite(id: number, data: string): Promise<void> {
  if (inTauri) await invoke("pty_write", { id, data });
}

export async function ptyResize(id: number, rows: number, cols: number): Promise<void> {
  if (inTauri) await invoke("pty_resize", { id, rows, cols });
}

export async function getTranscript(session: string): Promise<TranscriptEntry[]> {
  return inTauri ? invoke<TranscriptEntry[]>("get_transcript", { session }) : [];
}

// ---- git (F1) --------------------------------------------------------------------------------

export interface GitFile {
  path: string;
  staged: boolean;
  state: string;
}
export interface GitStatus {
  is_repo: boolean;
  branch: string;
  ahead: number;
  behind: number;
  files: GitFile[];
}

export async function gitStatus(cwd: string): Promise<GitStatus> {
  return inTauri
    ? invoke<GitStatus>("git_status", { cwd })
    : { is_repo: false, branch: "", ahead: 0, behind: 0, files: [] };
}

export interface Checkpoint {
  id: string;
  refname: string;
  commit: string;
  message: string;
}

export async function gitCheckpoint(cwd: string, message: string): Promise<Checkpoint | null> {
  return inTauri ? invoke<Checkpoint>("git_checkpoint", { cwd, message }) : null;
}
export async function gitCheckpoints(cwd: string): Promise<Checkpoint[]> {
  return inTauri ? invoke<Checkpoint[]>("git_checkpoints", { cwd }) : [];
}
export async function gitDiff(cwd: string, path: string | null): Promise<string> {
  return inTauri ? invoke<string>("git_diff", { cwd, path }) : "";
}
export async function gitDiffSince(cwd: string, commit: string): Promise<string> {
  return inTauri ? invoke<string>("git_diff_since", { cwd, commit }) : "";
}
export async function gitRevert(cwd: string, commit: string): Promise<void> {
  if (inTauri) await invoke("git_revert", { cwd, commit });
}
export async function gitCommit(cwd: string, message: string): Promise<string> {
  return inTauri ? invoke<string>("git_commit", { cwd, message }) : "";
}
export async function gitPush(cwd: string): Promise<string> {
  return inTauri ? invoke<string>("git_push", { cwd }) : "";
}

// ---- keybindings (F2) ------------------------------------------------------------------------

export type KeymapEntry = [action: string, key: string, label: string];

const DEFAULT_KEYMAP: KeymapEntry[] = [
  ["run", "Mod+Enter", "Run prompt"],
  ["new_session", "Mod+N", "New session"],
  ["cancel", "Mod+.", "Cancel turn"],
  ["toggle_terminal", "Mod+J", "Toggle terminal"],
  ["toggle_browser", "Mod+B", "Toggle browser"],
  ["open_skill_picker", "Mod+/", "Open skill picker"],
  ["open_settings", "Mod+,", "Open settings"],
  ["focus_editor", "Mod+E", "Focus editor"],
  ["cycle_permission_mode", "Mod+K", "Cycle permission mode"],
  ["refresh_git", "Mod+G", "Refresh git status"],
];

export async function getKeymap(): Promise<KeymapEntry[]> {
  return inTauri ? invoke<KeymapEntry[]>("get_keymap") : DEFAULT_KEYMAP;
}

export async function setKeymap(action: string, key: string): Promise<void> {
  if (inTauri) await invoke("set_keymap", { action, key });
}

// ---- browser annotate (F3/F4) ----------------------------------------------------------------

export interface Annotation {
  url: string;
  note: string;
  selector: string | null;
  selected_text: string | null;
}

// ---- skill market (F5) -----------------------------------------------------------------------

export interface MarketItem {
  id: string;
  name: string;
  description: string;
  author: string;
  tags: string[];
  icon: string | null;
  kind: string;
  installed: boolean;
}

const FALLBACK_MARKET: MarketItem[] = [
  { id: "architect", name: "System Architect", description: "Design before coding.", author: "codetwo", tags: ["design"], icon: "🏛️", kind: "fragment", installed: false },
  { id: "test-suite", name: "Test Suite Author", description: "Thorough deterministic tests.", author: "codetwo", tags: ["testing"], icon: "🧪", kind: "fragment", installed: false },
  { id: "browser-tool", name: "Browser Tool (MCP)", description: "Give the agent a browser.", author: "codetwo", tags: ["mcp", "browser"], icon: "🌐", kind: "mcp", installed: false },
];

export async function marketCatalog(): Promise<MarketItem[]> {
  return inTauri ? invoke<MarketItem[]>("market_catalog") : FALLBACK_MARKET;
}

export async function marketInstall(id: string): Promise<void> {
  if (inTauri) await invoke("market_install", { id });
}

// ---- remote control (F10) --------------------------------------------------------------------

export interface RemoteInfo {
  url: string;
  token: string;
  port: number;
}

export async function startRemote(port?: number): Promise<RemoteInfo | null> {
  return inTauri ? invoke<RemoteInfo>("start_remote", { port: port ?? null }) : null;
}

export async function remoteStatus(): Promise<RemoteInfo | null> {
  return inTauri ? invoke<RemoteInfo | null>("remote_status") : null;
}

// ---- issues (F14) ----------------------------------------------------------------------------

export interface Issue {
  id: string;
  title: string;
  state: string;
  url: string;
  body: string;
  source: string;
}

export async function ghAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("gh_available") : false;
}
export async function listGithubIssues(cwd: string, limit = 30): Promise<Issue[]> {
  return inTauri ? invoke<Issue[]>("list_github_issues", { cwd, limit }) : [];
}
export async function listLinearIssues(token: string, limit = 30): Promise<Issue[]> {
  return inTauri ? invoke<Issue[]>("list_linear_issues", { token, limit }) : [];
}
export async function issueContext(issue: Issue): Promise<string> {
  if (inTauri) return invoke<string>("issue_context", { issue });
  return `**${issue.source} #${issue.id}** — ${issue.title} (${issue.state})\n${issue.url}`;
}

// ---- compiled-prompt preview (F13) -----------------------------------------------------------

export interface CompiledPreview {
  prompt: string;
  mcp_servers: string[];
  agent_skills: string[];
  files: string[];
  unresolved: string[];
}

export async function compileDoc(doc: DocBlock[], cwd?: string | null): Promise<CompiledPreview> {
  if (inTauri) return invoke<CompiledPreview>("compile_doc", { doc, cwd: cwd ?? null });
  const describe = (b: DocBlock) =>
    b.type === "text" ? b.text : b.type === "skill" ? `[skill:${b.skill_id}]` : `[@${b.path}]`;
  return {
    prompt: doc.map(describe).join("\n\n"),
    mcp_servers: [],
    agent_skills: [],
    files: doc.flatMap((b) => (b.type === "file" ? [b.path] : [])),
    unresolved: [],
  };
}

// ---- workspace files & rules (G1/G2) ---------------------------------------------------------

const FALLBACK_FILES = ["src/main.rs", "src/lib.rs", "README.md"];

export async function listFiles(cwd: string, query: string, limit = 50): Promise<string[]> {
  if (!inTauri) return FALLBACK_FILES.filter((f) => f.includes(query));
  return invoke<string[]>("list_files", { cwd, query, limit });
}

export async function listRules(cwd: string): Promise<string[]> {
  return inTauri ? invoke<string[]>("list_rules", { cwd }) : [];
}

// ---- session management (G5) -----------------------------------------------------------------

export async function renameSession(session: string, title: string): Promise<void> {
  if (inTauri) await invoke("rename_session", { session, title });
}
export async function archiveSession(session: string, archived: boolean): Promise<void> {
  if (inTauri) await invoke("archive_session", { session, archived });
}
export async function listArchivedSessions(): Promise<SessionInfo[]> {
  return inTauri ? invoke<SessionInfo[]>("list_archived_sessions") : [];
}

// ---- PR + commit message (G6) ------------------------------------------------------------------

export async function gitCreatePr(cwd: string, title: string, body: string): Promise<string> {
  return inTauri ? invoke<string>("git_create_pr", { cwd, title, body }) : "";
}
export async function gitSuggestCommit(cwd: string): Promise<string> {
  return inTauri ? invoke<string>("git_suggest_commit", { cwd }) : "chore: update";
}

export async function browserContext(annotation: Annotation): Promise<string> {
  if (inTauri) return invoke<string>("browser_context", { annotation });
  // Local fallback mirrors core::browser::Annotation::to_context.
  let s = `**Browser context** — ${annotation.url}`;
  if (annotation.selected_text) s += `\n- selected: “${annotation.selected_text}”`;
  if (annotation.note) s += `\n- note: ${annotation.note}`;
  return s;
}

export async function saveSkill(skill: Skill): Promise<void> {
  if (inTauri) await invoke("save_skill", { skill });
}

export async function deleteSkill(id: string): Promise<void> {
  if (inTauri) await invoke("delete_skill", { id });
}

export async function onEngineEvent(cb: (ev: CoreEvent) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<CoreEvent>("engine-event", (e) => cb(e.payload));
}

export async function onPtyOutput(cb: (p: PtyOutput) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<PtyOutput>("pty-output", (e) => cb(e.payload));
}

export function providerLabel(p: string | { custom: string }): string {
  return typeof p === "string" ? p : p.custom;
}
