import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

// Typed bridge to the Rust core. In a later pass this is generated by tauri-specta; hand-written now.

export interface ProviderInfo {
  id: string;
  display_name: string;
  available: boolean;
  needs_node: boolean;
}

export interface SkillInfo {
  id: string;
  name: string;
  description: string;
  icon: string | null;
  kind: string;
}

export interface SessionInfo {
  id: string;
  title: string;
  provider: string | { custom: string };
  model: string | null;
  cwd: string;
  worktree_path: string | null;
  permission_mode: string;
  acp_session_id: string | null;
  created_at: number;
}

/// A workspace the user works in. The path is the identity — one directory is one project.
export interface Project {
  path: string;
  name: string;
  last_opened_at: number;
}

/// One model an agent offers. ACP's model API is UNSTABLE and most adapters don't implement it,
/// so a session may legitimately have none — the picker says so rather than showing an empty list.
export interface ModelChoice {
  id: string;
  name: string;
  description: string | null;
}

/// Neutral document shape the editor serializes into; matches core `DocBlock` serde.
export type DocBlock =
  | { type: "text"; text: string }
  | { type: "skill"; skill_id: string; params: Record<string, string> }
  | { type: "file"; path: string }
  | { type: "image"; path: string };

/// One-line description of a doc block, used for summaries and browser-mode previews.
export function describeBlock(b: DocBlock): string {
  switch (b.type) {
    case "text":
      return b.text;
    case "skill":
      return `[skill:${b.skill_id}]`;
    case "file":
      return `[@${b.path}]`;
    case "image":
      return `[img:${b.path}]`;
  }
}

/// Mirrors core `Event` (tagged by `event`, snake_case).
export type CoreEvent =
  | { event: "session_created"; session: string }
  | { event: "agent_text"; session: string; message_id: string; text: string }
  | { event: "agent_thought"; session: string; text: string }
  | { event: "tool_call"; session: string; id: string; title: string; status: string }
  | { event: "plan"; session: string; entries: string[] }
  | { event: "permission_request"; session: string; request_id: string; title: string; options: [string, string][] }
  | { event: "usage"; session: string; input_tokens: number; output_tokens: number }
  | { event: "models"; session: string; available: ModelChoice[]; current: string }
  | { event: "turn_ended"; session: string; stop_reason: string }
  | { event: "error"; session: string | null; message: string };

export interface PtyOutput {
  id: number;
  data: string;
}

/// Mirrors core `Part` (tagged by `kind`).
export type Part =
  | { kind: "text"; text: string }
  | { kind: "reasoning"; text: string }
  | { kind: "tool_call"; id: string; title: string; status: string }
  | { kind: "plan"; entries: string[] };

export type TranscriptEntry = [string, Part]; // [role, part]

export type SkillPayload =
  | { kind: "fragment"; text: string }
  | { kind: "macro"; template: string; slots: string[] };

export interface Skill {
  id: string;
  name: string;
  description: string;
  icon: string | null;
  payload: SkillPayload;
}

// True only inside the Tauri webview; lets `vite build`/`preview` run in a plain browser.
const inTauri = typeof (globalThis as { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__ !== "undefined";

const FALLBACK_PROVIDERS: ProviderInfo[] = [
  { id: "claude_code", display_name: "Claude Code", available: false, needs_node: true },
  { id: "codex", display_name: "OpenAI Codex", available: false, needs_node: true },
  { id: "grok", display_name: "Grok", available: false, needs_node: false },
  { id: "cursor", display_name: "Cursor", available: false, needs_node: false },
  { id: "opencode", display_name: "OpenCode", available: false, needs_node: false },
];

const FALLBACK_SKILLS: SkillInfo[] = [
  { id: "reviewer", name: "Code Reviewer", description: "Meticulous reviewer", icon: "🔍", kind: "fragment" },
  { id: "test-writer", name: "Test Writer", description: "Thorough tests", icon: "🧪", kind: "fragment" },
  { id: "security-audit", name: "Security Audit", description: "Find vulns", icon: "🛡️", kind: "fragment" },
  { id: "commit-macro", name: "Commit Message", description: "Commit macro", icon: "📝", kind: "macro" },
];

export async function listProviders(): Promise<ProviderInfo[]> {
  return inTauri ? invoke<ProviderInfo[]>("list_providers") : FALLBACK_PROVIDERS;
}

export async function listSkills(): Promise<SkillInfo[]> {
  return inTauri ? invoke<SkillInfo[]>("list_skills") : FALLBACK_SKILLS;
}

export async function listSessions(): Promise<SessionInfo[]> {
  return inTauri ? invoke<SessionInfo[]>("list_sessions") : [];
}

export async function newSession(provider: string, cwd: string, useWorktree: boolean): Promise<void> {
  if (inTauri) await invoke("new_session", { provider, cwd, useWorktree });
}

export async function submitPrompt(session: string, doc: DocBlock[]): Promise<void> {
  if (inTauri) await invoke("submit_prompt", { session, doc });
}

export async function answerPermission(session: string, requestId: string, optionId: string | null): Promise<void> {
  if (inTauri) await invoke("answer_permission", { session, requestId, optionId });
}

export async function setPermissionMode(session: string, mode: string): Promise<void> {
  if (inTauri) await invoke("set_permission_mode", { session, mode });
}

/// One entry in a directory listing, for the file tree in the side dock.
export interface DirEntry {
  name: string;
  path: string;
  is_dir: boolean;
}

/** One directory level. The tree expands lazily, so nothing is capped or silently truncated. */
export async function listDir(cwd: string, path: string): Promise<DirEntry[]> {
  return inTauri ? invoke<DirEntry[]>("list_dir", { cwd, path }) : [];
}

// ---- projects ----------------------------------------------------------------------------------

export async function listProjects(): Promise<Project[]> {
  return inTauri ? invoke<Project[]>("list_projects") : [];
}

/**
 * Native folder chooser. Returns null when the user cancels — which is a normal outcome, not an
 * error. Outside Tauri there's no picker, so it resolves to null and the caller does nothing.
 */
export async function pickDirectory(): Promise<string | null> {
  if (!inTauri) return null;
  const { open } = await import("@tauri-apps/plugin-dialog");
  const picked = await open({ directory: true, multiple: false, title: "Choose a project folder" });
  return typeof picked === "string" ? picked : null;
}

/** Returns the resolved absolute path, which is the project's identity. */
export async function addProject(path: string, name?: string): Promise<string> {
  return inTauri ? invoke<string>("add_project", { path, name: name ?? null }) : path;
}

export async function openProject(path: string): Promise<void> {
  if (inTauri) await invoke("open_project", { path });
}

export async function renameProject(path: string, name: string): Promise<void> {
  if (inTauri) await invoke("rename_project", { path, name });
}

export async function removeProject(path: string): Promise<void> {
  if (inTauri) await invoke("remove_project", { path });
}

/** Where a new session should start. Resolved by the core, never `"."` — see `default_cwd`. */
export async function defaultCwd(): Promise<string> {
  return inTauri ? invoke<string>("default_cwd") : ".";
}

export async function setModel(session: string, model: string): Promise<void> {
  if (inTauri) await invoke("set_model", { session, model });
}

export async function cancelTurn(session: string): Promise<void> {
  if (inTauri) await invoke("cancel_turn", { session });
}

export async function ptySpawn(
  id: number,
  cwd: string | null,
  rows: number,
  cols: number,
  tmuxSession?: string | null,
): Promise<void> {
  if (inTauri) await invoke("pty_spawn", { id, cwd, rows, cols, tmuxSession: tmuxSession ?? null });
}

export async function tmuxAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("tmux_available") : false;
}

export async function ptyWrite(id: number, data: string): Promise<void> {
  if (inTauri) await invoke("pty_write", { id, data });
}

export async function ptyResize(id: number, rows: number, cols: number): Promise<void> {
  if (inTauri) await invoke("pty_resize", { id, rows, cols });
}

export async function getTranscript(session: string): Promise<TranscriptEntry[]> {
  return inTauri ? invoke<TranscriptEntry[]>("get_transcript", { session }) : [];
}

// ---- git (F1) --------------------------------------------------------------------------------

export interface GitFile {
  path: string;
  staged: boolean;
  state: string;
}
export interface GitStatus {
  is_repo: boolean;
  branch: string;
  ahead: number;
  behind: number;
  files: GitFile[];
}

export async function gitStatus(cwd: string): Promise<GitStatus> {
  return inTauri
    ? invoke<GitStatus>("git_status", { cwd })
    : { is_repo: false, branch: "", ahead: 0, behind: 0, files: [] };
}

export interface Checkpoint {
  id: string;
  refname: string;
  commit: string;
  message: string;
}

export async function gitCheckpoint(cwd: string, message: string): Promise<Checkpoint | null> {
  return inTauri ? invoke<Checkpoint>("git_checkpoint", { cwd, message }) : null;
}
export async function gitCheckpoints(cwd: string): Promise<Checkpoint[]> {
  return inTauri ? invoke<Checkpoint[]>("git_checkpoints", { cwd }) : [];
}
export async function gitDiff(cwd: string, path: string | null): Promise<string> {
  return inTauri ? invoke<string>("git_diff", { cwd, path }) : "";
}
export async function gitDiffSince(cwd: string, commit: string): Promise<string> {
  return inTauri ? invoke<string>("git_diff_since", { cwd, commit }) : "";
}
export async function gitRevert(cwd: string, commit: string): Promise<void> {
  if (inTauri) await invoke("git_revert", { cwd, commit });
}
export async function gitCommit(cwd: string, message: string): Promise<string> {
  return inTauri ? invoke<string>("git_commit", { cwd, message }) : "";
}
export async function gitPush(cwd: string): Promise<string> {
  return inTauri ? invoke<string>("git_push", { cwd }) : "";
}

// ---- keybindings (F2) ------------------------------------------------------------------------

export type KeymapEntry = [action: string, key: string, label: string];

// Mirrors `Action::default_key()` in crates/core/src/keymap.rs — keep the two in step. This is only
// the browser-preview fallback; inside Tauri the real keymap (with user overrides) comes from core.
export const DEFAULT_KEYMAP: KeymapEntry[] = [
  ["run", "Mod+Enter", "Run prompt"],
  ["new_session", "Mod+N", "New session"],
  ["cancel", "Mod+.", "Cancel turn"],
  ["toggle_terminal", "Mod+J", "Toggle terminal"],
  ["toggle_browser", "Mod+B", "Toggle browser"],
  ["toggle_git", "Mod+Shift+B", "Toggle git panel"],
  ["close_panel", "Escape", "Close side panel"],
  ["open_skill_picker", "Mod+/", "Open skill picker"],
  ["focus_editor", "Mod+E", "Focus editor"],
  ["toggle_doc_mode", "Mod+Shift+E", "Expand document to full height"],
  ["open_command_palette", "Mod+K", "Command palette"],
  ["open_source_control", "Mod+Shift+G", "Source control"],
  ["open_market", "Mod+Shift+M", "Open skill market"],
  ["open_files", "Mod+P", "Browse workspace files"],
  ["open_issues", "Mod+Shift+I", "Open issues"],
  ["open_usage", "Mod+Shift+U", "Open usage"],
  ["open_settings", "Mod+,", "Open settings"],
  ["cycle_permission_mode", "Mod+Shift+P", "Cycle permission mode"],
  ["refresh_git", "Mod+G", "Refresh git status"],
  ["prev_session", "Mod+Alt+ArrowUp", "Previous session"],
  ["next_session", "Mod+Alt+ArrowDown", "Next session"],
];

export async function getKeymap(): Promise<KeymapEntry[]> {
  return inTauri ? invoke<KeymapEntry[]>("get_keymap") : DEFAULT_KEYMAP;
}

export async function setKeymap(action: string, key: string): Promise<void> {
  if (inTauri) await invoke("set_keymap", { action, key });
}

// ---- browser annotate (F3/F4) ----------------------------------------------------------------

export interface Annotation {
  url: string;
  note: string;
  selector: string | null;
  selected_text: string | null;
}

// ---- skill market (F5) -----------------------------------------------------------------------

export interface MarketItem {
  id: string;
  name: string;
  description: string;
  author: string;
  tags: string[];
  icon: string | null;
  kind: string;
  installed: boolean;
}

const FALLBACK_MARKET: MarketItem[] = [
  { id: "architect", name: "System Architect", description: "Design before coding.", author: "codetwo", tags: ["design"], icon: "🏛️", kind: "fragment", installed: false },
  { id: "test-suite", name: "Test Suite Author", description: "Thorough deterministic tests.", author: "codetwo", tags: ["testing"], icon: "🧪", kind: "fragment", installed: false },
  { id: "browser-tool", name: "Browser Tool (MCP)", description: "Give the agent a browser.", author: "codetwo", tags: ["mcp", "browser"], icon: "🌐", kind: "mcp", installed: false },
];

export async function marketCatalog(): Promise<MarketItem[]> {
  return inTauri ? invoke<MarketItem[]>("market_catalog") : FALLBACK_MARKET;
}

export async function marketInstall(id: string): Promise<void> {
  if (inTauri) await invoke("market_install", { id });
}

// ---- remote control (F10) --------------------------------------------------------------------

export interface RemoteInfo {
  url: string;
  token: string;
  port: number;
}

export async function startRemote(port?: number): Promise<RemoteInfo | null> {
  return inTauri ? invoke<RemoteInfo>("start_remote", { port: port ?? null }) : null;
}

export async function remoteStatus(): Promise<RemoteInfo | null> {
  return inTauri ? invoke<RemoteInfo | null>("remote_status") : null;
}

// ---- issues (F14) ----------------------------------------------------------------------------

export interface Issue {
  id: string;
  title: string;
  state: string;
  url: string;
  body: string;
  source: string;
}

export async function ghAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("gh_available") : false;
}
export async function listGithubIssues(cwd: string, limit = 30): Promise<Issue[]> {
  return inTauri ? invoke<Issue[]>("list_github_issues", { cwd, limit }) : [];
}
export async function listLinearIssues(token: string, limit = 30): Promise<Issue[]> {
  return inTauri ? invoke<Issue[]>("list_linear_issues", { token, limit }) : [];
}
export async function issueContext(issue: Issue): Promise<string> {
  if (inTauri) return invoke<string>("issue_context", { issue });
  return `**${issue.source} #${issue.id}** — ${issue.title} (${issue.state})\n${issue.url}`;
}

// ---- compiled-prompt preview (F13) -----------------------------------------------------------

export interface CompiledPreview {
  prompt: string;
  mcp_servers: string[];
  agent_skills: string[];
  files: string[];
  images: string[];
  unresolved: string[];
}

export async function compileDoc(doc: DocBlock[], cwd?: string | null): Promise<CompiledPreview> {
  if (inTauri) return invoke<CompiledPreview>("compile_doc", { doc, cwd: cwd ?? null });
  return {
    prompt: doc.map(describeBlock).join("\n\n"),
    mcp_servers: [],
    agent_skills: [],
    files: doc.flatMap((b) => (b.type === "file" ? [b.path] : [])),
    images: doc.flatMap((b) => (b.type === "image" ? [b.path] : [])),
    unresolved: [],
  };
}

// ---- sandbox + project scripts (G7/G8) ---------------------------------------------------------

export type Sandbox = "read_only" | "workspace_write" | "danger_full_access";

export async function setSandbox(session: string, sandbox: Sandbox): Promise<void> {
  if (inTauri) await invoke("set_sandbox", { session, sandbox });
}

export interface ProjectScript {
  id: string;
  name: string;
  command: string;
  run_on_worktree_create: boolean;
}

export async function listProjectScripts(cwd: string): Promise<ProjectScript[]> {
  return inTauri ? invoke<ProjectScript[]>("list_project_scripts", { cwd }) : [];
}

export async function runProjectScript(cwd: string, id: string): Promise<string> {
  return inTauri ? invoke<string>("run_project_script", { cwd, id }) : "";
}

// ---- voice input (G11) -------------------------------------------------------------------------

/// Whether the core has a local transcriber configured (CODETWO_TRANSCRIBE_CMD or an auto-detected
/// whisper binary). The UI prefers the webview's own speech recognition when present.
export async function voiceAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("voice_available") : false;
}

export async function transcribeAudio(bytes: Uint8Array, ext = "webm"): Promise<string> {
  if (!inTauri) return "";
  return invoke<string>("transcribe_audio", { bytes: Array.from(bytes), ext });
}

// ---- usage tracking (G12) ----------------------------------------------------------------------

export interface UsageWindow {
  label: string;
  window_secs: number;
  input_tokens: number;
  /// Cache reads — reported but excluded from `total_tokens`.
  cached_tokens: number;
  output_tokens: number;
  total_tokens: number;
  limit: number | null;
  fraction: number | null;
  resets_in_secs: number;
}

export interface UsageReport {
  windows: UsageWindow[];
  by_source: [string, number][];
  transcripts: number;
}

const EMPTY_USAGE: UsageReport = {
  windows: [
    { label: "5h session", window_secs: 18000, input_tokens: 0, cached_tokens: 0, output_tokens: 0, total_tokens: 0, limit: null, fraction: null, resets_in_secs: 0 },
    { label: "week", window_secs: 604800, input_tokens: 0, cached_tokens: 0, output_tokens: 0, total_tokens: 0, limit: null, fraction: null, resets_in_secs: 0 },
    { label: "month", window_secs: 2592000, input_tokens: 0, cached_tokens: 0, output_tokens: 0, total_tokens: 0, limit: null, fraction: null, resets_in_secs: 0 },
  ],
  by_source: [],
  transcripts: 0,
};

export async function usageReport(): Promise<UsageReport> {
  return inTauri ? invoke<UsageReport>("usage_report") : EMPTY_USAGE;
}

// ---- workspace files & rules (G1/G2) ---------------------------------------------------------

const FALLBACK_FILES = ["src/main.rs", "src/lib.rs", "README.md"];

export async function listFiles(cwd: string, query: string, limit = 50): Promise<string[]> {
  if (!inTauri) return FALLBACK_FILES.filter((f) => f.includes(query));
  return invoke<string[]>("list_files", { cwd, query, limit });
}

export async function listRules(cwd: string): Promise<string[]> {
  return inTauri ? invoke<string[]>("list_rules", { cwd }) : [];
}

// ---- session management (G5) -----------------------------------------------------------------

export async function renameSession(session: string, title: string): Promise<void> {
  if (inTauri) await invoke("rename_session", { session, title });
}
export async function archiveSession(session: string, archived: boolean): Promise<void> {
  if (inTauri) await invoke("archive_session", { session, archived });
}
export async function listArchivedSessions(): Promise<SessionInfo[]> {
  return inTauri ? invoke<SessionInfo[]>("list_archived_sessions") : [];
}

// ---- PR + commit message (G6) ------------------------------------------------------------------

export async function gitCreatePr(cwd: string, title: string, body: string): Promise<string> {
  return inTauri ? invoke<string>("git_create_pr", { cwd, title, body }) : "";
}
export async function gitSuggestCommit(cwd: string): Promise<string> {
  return inTauri ? invoke<string>("git_suggest_commit", { cwd }) : "chore: update";
}

export async function browserContext(annotation: Annotation): Promise<string> {
  if (inTauri) return invoke<string>("browser_context", { annotation });
  // Local fallback mirrors core::browser::Annotation::to_context.
  let s = `**Browser context** — ${annotation.url}`;
  if (annotation.selected_text) s += `\n- selected: “${annotation.selected_text}”`;
  if (annotation.note) s += `\n- note: ${annotation.note}`;
  return s;
}

export async function saveSkill(skill: Skill): Promise<void> {
  if (inTauri) await invoke("save_skill", { skill });
}

export async function deleteSkill(id: string): Promise<void> {
  if (inTauri) await invoke("delete_skill", { id });
}

export async function onEngineEvent(cb: (ev: CoreEvent) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<CoreEvent>("engine-event", (e) => cb(e.payload));
}

export async function onPtyOutput(cb: (p: PtyOutput) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<PtyOutput>("pty-output", (e) => cb(e.payload));
}

export function providerLabel(p: string | { custom: string }): string {
  return typeof p === "string" ? p : p.custom;
}
