import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";

// Typed bridge to the Rust core. In a later pass this is generated by tauri-specta; hand-written now.

export interface ProviderInfo {
  id: string;
  display_name: string;
  available: boolean;
  needs_node: boolean;
  /// The core's built-in models for this provider — what the picker offers when the provider
  /// reports none of its own over ACP. Empty only for providers we ship no list for.
  models: ModelChoice[];
  capabilities: ProviderCapability[];
}

export type ProviderCapabilityId =
  | "image_generation"
  | "computer_use"
  | "chrome_browser"
  | "codetwo_browser"
  | "sites";
export type CapabilityState = "ready" | "unverified" | "unavailable";

export interface ProviderCapability {
  id: ProviderCapabilityId;
  state: CapabilityState;
  version?: string | null;
  experimental: boolean;
  reason?: string | null;
  fix?: string | null;
}

type ProviderInfoWire = Omit<ProviderInfo, "capabilities"> & {
  capabilities?: ProviderCapability[] | null;
};

export function normalizeProviderInfo(provider: ProviderInfoWire): ProviderInfo {
  return { ...provider, capabilities: provider.capabilities ?? [] };
}

/** One typed macro slot as `list_skills` reports it (core `SlotDef`, Agent Scenes vocabulary). */
export interface MacroSlotInfo {
  id: string;
  label?: string;
  kind?: "text" | "multiline" | "select" | "file" | "artifact";
  options?: string[];
  required?: boolean;
  default?: string;
}

export interface SkillInfo {
  id: string;
  name: string;
  description: string;
  icon: string | null;
  kind: string;
  /// Harness display name ("Claude Code" …) for skills auto-discovered from a product's skill
  /// directory; null for library skills.
  source: string | null;
  /// Macro payload metadata so the `/` picker can render the R1 slot card without a second
  /// fetch. Absent for every other kind (and for backends predating the fields).
  macro_template?: string | null;
  macro_slots?: MacroSlotInfo[] | null;
}

export type PermissionMode = "ask" | "accept_edits" | "yolo";
export type Sandbox = "read_only" | "workspace_write" | "danger_full_access";

export interface ExecutionPolicy {
  mode: PermissionMode;
  sandbox: Sandbox;
}

export interface SessionInfo {
  id: string;
  title: string;
  title_origin: "default" | "automatic" | "manual";
  /** Pinned sessions stay above the active recency list for their project. */
  pinned: boolean;
  provider: string | { custom: string };
  model: string | null;
  cwd: string;
  worktree_path: string | null;
  /** Original selected project directory; `cwd` may instead point into an isolated worktree. */
  project_path: string | null;
  /** Exact local ref + commit used to create the isolated checkout. */
  worktree_baseline?: ResolvedWorktreeBaseline | null;
  /** Opaque persisted filesystem identity. Its presence distinguishes strongly verified rows. */
  worktree_identity?: Record<string, unknown> | null;
  permission_mode: PermissionMode;
  sandbox_policy: Sandbox;
  acp_session_id: string | null;
  memory_read: MemoryAccess;
  memory_write: MemoryAccess;
  created_at: number;
  /** Core-owned, revisioned run/input state; survives renderer and remote reconnects. */
  activity?: SessionActivity;
}

export type PendingInputKind = "permission";

export type PermissionContextKind =
  | "acp"
  | "mcp_elicitation"
  | "website_access"
  | "sensitive_web_action"
  | "computer_use_application"
  | "sites_mutation"
  | "sites_production";

export interface PermissionContext {
  kind: PermissionContextKind;
  server?: string | null;
  tool?: string | null;
  origin?: string | null;
  risk?: string | null;
  application?: string | null;
}

export interface PendingInput {
  input_id: string;
  kind: PendingInputKind;
  title: string;
  options: [string, string][];
  sequence: number;
  context?: PermissionContext;
}

export type RunFailureReason = "provider_error" | "interrupted";

export type SessionRunState =
  | { kind: "idle" }
  | { kind: "running"; turn_id: string; prompt_request_id?: string | null }
  | {
      kind: "awaiting_input";
      turn_id: string;
      prompt_request_id?: string | null;
      pending: PendingInput[];
    }
  | {
      kind: "failed";
      turn_id?: string | null;
      reason: RunFailureReason;
      message: string;
    };

export interface SessionActivity {
  revision: number;
  state: SessionRunState;
}

export type WorktreeBaselineKind = "current" | "origin_default";
export type ProjectWorktreeMode = "local" | WorktreeBaselineKind;

export interface ResolvedWorktreeBaseline {
  kind: WorktreeBaselineKind;
  ref: string;
  sha: string;
  display: string;
}

export interface WorktreeBaselineOption {
  kind: WorktreeBaselineKind;
  resolved: ResolvedWorktreeBaseline | null;
  unavailable_reason: string | null;
}

export type MemoryAccess = "inherit" | "allow" | "deny";

/// A workspace the user works in. The path is the identity — one directory is one project.
export interface Project {
  path: string;
  name: string;
  last_opened_at: number;
  /** Null follows the current draft/session; local is an explicit no-worktree default. */
  default_worktree_mode: ProjectWorktreeMode | null;
}

export interface MemorySettings {
  enabled: boolean;
  capture: boolean;
  inject: boolean;
  include_external_context: boolean;
}

export interface MemorySourceRef {
  session_id: string;
  part_seq: number;
}

export interface MemoryRecord {
  id: string;
  project_path: string;
  session_id: string | null;
  layer: "L0" | "L1" | "L2" | "L3";
  category: string;
  content: string;
  confidence: number;
  sources: MemorySourceRef[];
  pinned: boolean;
  active: boolean;
  created_at: number;
  updated_at: number;
  relevance: number | null;
  editable: boolean;
}

export interface MemoryStats {
  l0: number;
  l1: number;
  l2: number;
  l3: number;
  pending: number;
}

export interface MemoryReceiptItem {
  id: string;
  layer: "L0" | "L1" | "L2" | "L3";
  category: string;
  content: string;
  source: MemorySourceRef | null;
  relevance: number | null;
}

export interface MemoryReceipt {
  session_id: string;
  user_part_seq: number;
  estimated_tokens: number;
  items: MemoryReceiptItem[];
  created_at: number;
}

/// One model a session can run on. ACP's model API is UNSTABLE and most adapters don't report a
/// list, so these usually come from the core's built-in list for the provider instead.
export interface ModelChoice {
  id: string;
  name: string;
  description: string | null;
}

/// One session config selector the agent reports (ACP config options — the newer surface where
/// current adapters put the model picker and the reasoning/thought level).
export interface ConfigOptionInfo {
  id: string;
  name: string;
  /// Semantic hint from the spec: "model" | "mode" | "thought_level" | anything else.
  category: string | null;
  current: string;
  choices: ModelChoice[];
}

/// Neutral document shape the editor serializes into; matches core `DocBlock` serde.
export type DocBlock =
  | { type: "text"; text: string }
  | { type: "skill"; skill_id: string; params: Record<string, string> }
  | { type: "file"; path: string }
  | { type: "image"; path: string }
  | { type: "canvas"; id: string; frozen_revision: number; pixel_policy?: CanvasPixelPolicy }
  | { type: "session"; session_id: string }
  // R12: a referenced issue-tracker item with its snapshot embedded at insert time; mirrors core
  // `DocBlock::Issue`, which re-renders `issues::Issue::to_context` from exactly these fields.
  | { type: "issue"; source: string; id: string; title: string; url: string; body: string };

/// One-line description of a doc block, used for summaries and browser-mode previews.
export function describeBlock(b: DocBlock): string {
  switch (b.type) {
    case "text":
      return b.text;
    case "skill":
      return `[skill:${b.skill_id}]`;
    case "file":
      return `[@${b.path}]`;
    case "image":
      return `[img:${b.path}]`;
    case "canvas":
      return `[canvas:${b.id}@${b.frozen_revision}]`;
    case "session":
      return `[chat:${b.session_id.slice(0, 8)}]`;
    case "issue":
      return `[issue:${b.source}#${b.id}]`;
  }
}

/// Mirrors core `Event` (tagged by `event`, snake_case).
export type CoreEvent =
  | {
      event: "session_created";
      session: string;
      cwd?: string;
      project_path?: string | null;
      worktree_path?: string | null;
      worktree_baseline?: ResolvedWorktreeBaseline | null;
      request_id?: string | null;
    }
  | { event: "memory_context"; session: string; receipt: MemoryReceipt }
  | { event: "session_title_changed"; session: string; title: string }
  | { event: "session_activity_changed"; session: string; activity: SessionActivity }
  | {
      event: "turn_started";
      session: string;
      request_id?: string | null;
      transcript_seq?: number | null;
    }
  | {
      event: "agent_text";
      session: string;
      message_id: string;
      text: string;
      transcript_seq?: number | null;
    }
  | {
      event: "agent_thought";
      session: string;
      text: string;
      transcript_seq?: number | null;
    }
  | {
      event: "tool_call";
      session: string;
      id: string;
      title: string;
      status: string;
      kind?: string | null;
      agent_input?: unknown;
      outputs?: ToolOutput[];
      transcript_seq?: number | null;
    }
  | {
      event: "plan";
      session: string;
      entries: string[];
      transcript_seq?: number | null;
    }
  | {
      event: "permission_request";
      session: string;
      request_id: string;
      title: string;
      options: [string, string][];
      context?: PermissionContext;
    }
  | { event: "usage"; session: string; input_tokens: number; output_tokens: number }
  | {
      event: "context_window";
      session: string;
      used_tokens: number;
      context_window: number;
      cost_usd?: number | null;
    }
  | { event: "models"; session: string; available: ModelChoice[]; current: string }
  | { event: "config_options"; session: string; options: ConfigOptionInfo[] }
  | {
      event: "execution_policy_changed";
      session: string;
      policy: ExecutionPolicy;
      request_id?: string | null;
    }
  | { event: "turn_ended"; session: string; stop_reason: string }
  | {
      event: "error";
      session: string | null;
      message: string;
      terminal: boolean;
      request_id?: string | null;
    }
  | {
      event: "test_signal";
      session: string;
      tool_call_id: string;
      command: string;
      passed: boolean;
      exit_code?: number | null;
    }
  | {
      event: "artifact_produced";
      session: string;
      scene_ref: string;
      artifact_key: string;
      kind: string;
      version: number;
      record_id: number;
    }
  | {
      event: "exit_criteria_met";
      session: string;
      scene_ref: string;
      satisfied: string[];
      unverified: string[];
      state_key: string;
    }
  | {
      event: "hook_suggestion";
      session: string;
      scene_ref: string;
      on: string;
      kind: string;
      target_scene?: string | null;
      carry?: string[];
      message?: string | null;
      pipeline_instance?: string | null;
      to_stage?: string | null;
      state_key: string;
    }
  | { event: "hook_turn_started"; session: string; scene_ref: string; macro_id: string }
  | {
      event: "session_cost";
      session: string;
      input_tokens: number;
      output_tokens: number;
      cost_usd?: number | null;
      burn_rate_usd_per_hour?: number | null;
      priced: boolean;
    };

export interface PtyOutput {
  id: string;
  data: string;
}

/** The title the child set (OSC 0/2), or its working directory (OSC 7). */
export interface PtyTitle {
  id: string;
  title: string;
}

export interface PtyAttach {
  /** False when we re-attached to a terminal that was already running. */
  created: boolean;
  /** VT sequences reproducing the terminal's scrollback, screen, and cursor. */
  restore: string;
}

/// Mirrors core `Part` (tagged by `kind`).
export type Part =
  | { kind: "text"; text: string }
  | { kind: "prompt"; text: string; display: string }
  | { kind: "reasoning"; text: string }
  | {
      kind: "tool_call";
      id: string;
      title: string;
      status: string;
      tool_kind?: string | null;
      agent_input?: unknown;
      outputs?: ToolOutput[];
    }
  | { kind: "plan"; entries: string[] };

export interface ArtifactRef {
  id: string;
  mime_type: string;
  bytes: number;
  width: number;
  height: number;
  display_name: string;
}

export type ToolOutput =
  | { type: "text"; text: string }
  | { type: "image"; artifact: ArtifactRef }
  | { type: "resource_link"; name: string; uri: string; mime_type?: string | null };

/** One durable transcript row. `seq` is stable within a session and orders snapshot/live merge. */
export interface TranscriptEntry {
  seq: number;
  role: "user" | "agent";
  part: Part;
}

/** A page never begins in the middle of a user turn. `next_before` is exclusive. */
export interface TranscriptPage {
  entries: TranscriptEntry[];
  next_before: number | null;
  snapshot_through: number | null;
}

export type SkillPayload =
  | { kind: "fragment"; text: string }
  // Core's untagged slot deserializer accepts bare legacy ids and full slot objects (R2).
  | { kind: "macro"; template: string; slots: (string | MacroSlotInfo)[] };

export interface Skill {
  id: string;
  name: string;
  description: string;
  icon: string | null;
  source?: string | null;
  payload: SkillPayload;
}

// True only inside the Tauri webview; lets `vite build`/`preview` run in a plain browser.
const inTauri = typeof (globalThis as { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__ !== "undefined";

/** False when the UI runs in a plain browser (`bun run dev`), where no native commands exist. */
export const isDesktop = inTauri;

const FALLBACK_PROVIDERS: ProviderInfo[] = [
  { id: "claude_code", display_name: "Claude Code", available: false, needs_node: true, models: [], capabilities: [] },
  { id: "codex", display_name: "OpenAI Codex", available: false, needs_node: true, models: [], capabilities: [] },
  { id: "grok", display_name: "Grok", available: false, needs_node: false, models: [], capabilities: [] },
  { id: "cursor", display_name: "Cursor", available: false, needs_node: false, models: [], capabilities: [] },
  { id: "opencode", display_name: "OpenCode", available: false, needs_node: false, models: [], capabilities: [] },
  { id: "pi", display_name: "Pi", available: false, needs_node: true, models: [], capabilities: [] },
  { id: "kimi", display_name: "Kimi", available: false, needs_node: false, models: [], capabilities: [] },
  { id: "zcode", display_name: "ZCode (GLM)", available: false, needs_node: true, models: [], capabilities: [] },
];

const FALLBACK_SKILLS: SkillInfo[] = [
  { id: "reviewer", name: "Code Reviewer", description: "Meticulous reviewer", icon: "🔍", kind: "fragment", source: null },
  { id: "test-writer", name: "Test Writer", description: "Thorough tests", icon: "🧪", kind: "fragment", source: null },
  { id: "security-audit", name: "Security Audit", description: "Find vulns", icon: "🛡️", kind: "fragment", source: null },
  {
    id: "commit-macro", name: "Commit Message", description: "Commit macro", icon: "📝", kind: "macro", source: null,
    macro_template: "Write a {{style}} commit message for changes to {{scope}}.",
    macro_slots: [
      { id: "style", label: "Style", kind: "select", options: ["conventional", "descriptive"], required: true },
      { id: "scope", label: "Scope", kind: "text" },
    ],
  },
  { id: "demo:skill:review", name: "Release Review", description: "Review a release against its acceptance criteria", icon: null, kind: "agent_skill", source: "Plugin · Developer Toolkit" },
  { id: "demo:agent:research", name: "Researcher", description: "Collect primary evidence before implementation", icon: null, kind: "subagent", source: "Plugin · Developer Toolkit" },
  { id: "demo:mcp:docs", name: "docs-search", description: "MCP server from Developer Toolkit", icon: null, kind: "mcp", source: "Plugin · Developer Toolkit" },
];

export async function listProviders(): Promise<ProviderInfo[]> {
  const providers = inTauri
    ? await invoke<ProviderInfoWire[]>("list_providers")
    : FALLBACK_PROVIDERS;
  return providers.map(normalizeProviderInfo);
}

/// Passing a cwd makes the core rescan that workspace's harness skill directories
/// (.claude/skills, .codex/skills, …) before answering.
export async function listSkills(cwd?: string): Promise<SkillInfo[]> {
  return inTauri ? invoke<SkillInfo[]>("list_skills", { cwd: cwd ?? null }) : FALLBACK_SKILLS;
}

export async function listSessions(): Promise<SessionInfo[]> {
  return inTauri ? invoke<SessionInfo[]>("list_sessions") : [];
}

export async function getMemorySettings(): Promise<MemorySettings> {
  return inTauri
    ? invoke<MemorySettings>("memory_settings")
    : { enabled: true, capture: true, inject: true, include_external_context: true };
}

export async function saveMemorySettings(settings: MemorySettings): Promise<void> {
  if (inTauri) await invoke("set_memory_settings", { settings });
}

export async function listMemories(projectPath: string, limit = 100): Promise<MemoryRecord[]> {
  return inTauri ? invoke<MemoryRecord[]>("list_memories", { projectPath, limit }) : [];
}

export async function searchMemories(projectPath: string, query: string, limit = 50): Promise<MemoryRecord[]> {
  return inTauri ? invoke<MemoryRecord[]>("search_memories", { projectPath, query, limit }) : [];
}

export async function getMemoryStats(projectPath: string): Promise<MemoryStats> {
  return inTauri
    ? invoke<MemoryStats>("memory_stats", { projectPath })
    : { l0: 0, l1: 0, l2: 0, l3: 0, pending: 0 };
}

export async function addMemory(
  projectPath: string,
  category: string,
  content: string,
  pinned = true,
): Promise<MemoryRecord> {
  return invoke<MemoryRecord>("add_memory", { projectPath, category, content, pinned });
}

export async function setMemoryPinned(id: string, pinned: boolean): Promise<void> {
  if (inTauri) await invoke("set_memory_pinned", { id, pinned });
}

export async function setMemoryActive(id: string, active: boolean): Promise<void> {
  if (inTauri) await invoke("set_memory_active", { id, active });
}

export async function setSessionMemoryPolicy(
  session: string,
  read: MemoryAccess,
  write: MemoryAccess,
): Promise<void> {
  if (inTauri) await invoke("set_session_memory_policy", { session, read, write });
}

export async function listMemoryReceipts(session: string): Promise<MemoryReceipt[]> {
  return inTauri ? invoke<MemoryReceipt[]>("list_memory_receipts", { session }) : [];
}

export async function newSession(
  provider: string,
  cwd: string,
  worktreeBase: WorktreeBaselineKind | null,
  requestId: string,
  worktreeBaseSha?: string | null,
  initialPolicy?: ExecutionPolicy | null,
): Promise<void> {
  if (inTauri) {
    await invoke("new_session", {
      provider,
      cwd,
      useWorktree: worktreeBase !== null,
      worktreeBase,
      worktreeBaseSha: worktreeBaseSha ?? null,
      requestId,
      initialPolicy: initialPolicy ?? null,
    });
  }
}

/** Resolve selectable baselines from local refs only. This command never fetches. */
export async function listWorktreeBaselines(cwd: string): Promise<WorktreeBaselineOption[]> {
  return inTauri ? invoke<WorktreeBaselineOption[]>("list_worktree_baselines", { cwd }) : [];
}

export async function submitPrompt(session: string, doc: DocBlock[], requestId: string): Promise<void> {
  if (inTauri) await invoke("submit_prompt", { session, doc, requestId });
}

export async function answerPermission(session: string, requestId: string, optionId: string | null): Promise<void> {
  if (inTauri) await invoke("answer_permission", { session, requestId, optionId });
}

export async function setPermissionMode(session: string, mode: string): Promise<void> {
  if (inTauri) await invoke("set_permission_mode", { session, mode });
}

export async function setExecutionPolicy(
  session: string,
  mode: PermissionMode,
  sandbox: Sandbox,
  requestId: string,
): Promise<void> {
  if (inTauri) await invoke("set_execution_policy", { session, mode, sandbox, requestId });
}

/// One entry in a directory listing, for the file tree in the side dock.
export interface DirEntry {
  name: string;
  path: string;
  is_dir: boolean;
}

/** One directory level. The tree expands lazily, so nothing is capped or silently truncated. */
export async function listDir(cwd: string, path: string): Promise<DirEntry[]> {
  return inTauri ? invoke<DirEntry[]>("list_dir", { cwd, path }) : [];
}

/** Create an empty file. Rejects paths that already exist rather than overwriting. */
export async function createFile(cwd: string, path: string): Promise<void> {
  if (inTauri) await invoke("create_file", { cwd, path });
}

export async function createDir(cwd: string, path: string): Promise<void> {
  if (inTauri) await invoke("create_dir", { cwd, path });
}

/** Read a file for the viewer. Rejects binaries and oversized files rather than showing mojibake. */
export async function readText(cwd: string, path: string): Promise<string> {
  return inTauri ? invoke<string>("read_text", { cwd, path }) : "";
}

/**
 * Raw bytes, for the image preview. Comes back over Tauri's binary IPC channel as an ArrayBuffer;
 * older/other shapes (a plain number array) are normalized here so callers always get bytes.
 */
export async function readBinary(cwd: string, path: string): Promise<Uint8Array> {
  if (!inTauri) return new Uint8Array();
  const res = await invoke<ArrayBuffer | number[]>("read_binary", { cwd, path });
  return res instanceof ArrayBuffer ? new Uint8Array(res) : new Uint8Array(res);
}

export async function getArtifact(id: string): Promise<Uint8Array> {
  if (!inTauri) return new Uint8Array();
  const res = await invoke<ArrayBuffer | number[]>("get_artifact", { id });
  return res instanceof ArrayBuffer ? new Uint8Array(res) : new Uint8Array(res);
}

export async function saveArtifactAs(id: string, displayName: string): Promise<boolean> {
  if (!inTauri) return false;
  const { save } = await import("@tauri-apps/plugin-dialog");
  const destination = await save({ defaultPath: displayName });
  if (!destination) return false;
  await invoke("save_artifact_as", { id, destination });
  return true;
}

export async function revealArtifact(id: string): Promise<void> {
  if (inTauri) await invoke("reveal_artifact", { id });
}

export async function writeText(cwd: string, path: string, content: string): Promise<void> {
  if (inTauri) await invoke("write_text", { cwd, path, content });
}

function splitNativePath(path: string): { cwd: string; name: string } {
  const separator = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  if (separator < 0) return { cwd: ".", name: path };
  const windowsRoot = separator === 2 && path[1] === ":";
  const cwd = windowsRoot ? path.slice(0, separator + 1) : path.slice(0, separator) || path.slice(0, 1);
  return { cwd, name: path.slice(separator + 1) };
}

/** Native theme picker. `undefined` means the web build should use its hidden file input. */
export async function pickAppearanceThemeDocument(): Promise<string | null | undefined> {
  if (!inTauri) return undefined;
  const { open } = await import("@tauri-apps/plugin-dialog");
  const selected = await open({
    multiple: false,
    directory: false,
    title: "Import Code2 theme",
    filters: [{ name: "Code2 theme", extensions: ["json"] }],
  });
  if (typeof selected !== "string") return null;
  const { cwd, name } = splitNativePath(selected);
  return invoke<string>("read_text", { cwd, path: name });
}

export type AppearanceThemeSaveResult = "saved" | "cancelled" | "unsupported";

/** Saves through the OS dialog in Tauri; the web build falls back to a normal JSON download. */
export async function saveAppearanceThemeDocument(
  suggestedName: string,
  content: string,
): Promise<AppearanceThemeSaveResult> {
  if (!inTauri) return "unsupported";
  const { save } = await import("@tauri-apps/plugin-dialog");
  const selected = await save({
    title: "Export Code2 theme",
    defaultPath: suggestedName,
    filters: [{ name: "Code2 theme", extensions: ["json"] }],
  });
  if (typeof selected !== "string") return "cancelled";
  const { cwd, name } = splitNativePath(selected);
  try {
    await invoke("create_file", { cwd, path: name });
  } catch {
    // The save panel explicitly confirms replacement. An existing file is therefore expected.
  }
  await invoke("write_text", { cwd, path: name, content });
  return "saved";
}

/** Rename *and* move — a `to` with a different parent moves it. */
export async function renamePath(cwd: string, from: string, to: string): Promise<void> {
  if (inTauri) await invoke("rename_path", { cwd, from, to });
}

export async function copyPath(cwd: string, from: string, to: string): Promise<void> {
  if (inTauri) await invoke("copy_path", { cwd, from, to });
}

export async function deletePath(cwd: string, path: string): Promise<void> {
  if (inTauri) await invoke("delete_path", { cwd, path });
}

/** Open the webview inspector on the app's own UI. */
export async function openDevtools(): Promise<void> {
  if (inTauri) await invoke("open_devtools");
}

// ---- built-in browser --------------------------------------------------------------------------
// Each browser tab is a native child webview of the main window, not an iframe: the sites people
// actually open (github.com, google.com, anything with `X-Frame-Options: DENY`) refuse to be framed
// and render blank. The panel measures a placeholder in the DOM and keeps the native view pinned
// over it — see `browser/Browser.tsx` and `src-tauri/src/browser.rs`.

export interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** Create the tab's webview if needed, place it, and load `url`. Safe to call repeatedly. */
export async function browserOpen(label: string, url: string, r: Rect): Promise<void> {
  if (inTauri) await invoke("browser_open", { label, url, ...r });
}

export async function browserBounds(label: string, r: Rect): Promise<void> {
  if (inTauri) await invoke("browser_bounds", { label, ...r });
}

export async function browserNavigate(label: string, url: string): Promise<void> {
  if (inTauri) await invoke("browser_navigate", { label, url });
}

/** −1 is back, 1 is forward — the page's own history, not one we keep for it. */
export async function browserHistory(label: string, delta: number): Promise<void> {
  if (inTauri) await invoke("browser_history", { label, delta });
}

export async function browserReload(label: string): Promise<void> {
  if (inTauri) await invoke("browser_reload", { label });
}

/** Hide, not close: the page keeps its state, which is the point of tabs. */
export async function browserVisible(label: string, visible: boolean): Promise<void> {
  if (inTauri) await invoke("browser_visible", { label, visible });
}

export async function browserZoom(label: string, factor: number): Promise<void> {
  if (inTauri) await invoke("browser_zoom", { label, factor });
}

export async function browserDevtools(label: string): Promise<void> {
  if (inTauri) await invoke("browser_devtools", { label });
}

export async function browserClose(label: string): Promise<void> {
  if (inTauri) await invoke("browser_close", { label });
}

export async function browserCloseAll(): Promise<void> {
  if (inTauri) await invoke("browser_close_all");
}

export interface BrowserNav {
  label: string;
  url: string;
}

export interface BrowserTab {
  id: string;
  url: string;
  title: string;
  active: boolean;
  lease_session?: string | null;
  agent_active: boolean;
}

export async function browserRegistrySnapshot(): Promise<BrowserTab[]> {
  return inTauri
    ? invoke<BrowserTab[]>("browser_registry_snapshot")
    : [{ id: "browser-1", url: "about:blank", title: "", active: true, agent_active: false }];
}

export async function browserRegistryCreate(url: string): Promise<BrowserTab> {
  return inTauri
    ? invoke<BrowserTab>("browser_registry_create", { url })
    : { id: `browser-${Date.now()}`, url, title: "", active: true, agent_active: false };
}

export async function browserTakeControl(label: string): Promise<void> {
  if (inTauri) await invoke("browser_take_control", { label });
}

export async function browserPermissions(): Promise<string[]> {
  return inTauri ? invoke<string[]>("browser_permissions") : [];
}

export async function browserRevokePermission(origin: string): Promise<void> {
  if (inTauri) await invoke("browser_revoke_permission", { origin });
}

export async function onBrowserRegistry(cb: (tabs: BrowserTab[]) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<BrowserTab[]>("browser-registry", (event) => cb(event.payload));
}

export async function onBrowserAgentActivity(
  cb: (payload: { tabId: string }) => void,
): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<{ tabId: string }>("browser-agent-activity", (event) => cb(event.payload));
}

export async function onBrowserDownloadBlocked(
  cb: (payload: { label: string }) => void,
): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<{ label: string }>("browser-download-blocked", (event) => cb(event.payload));
}

// ---- in-page annotator -------------------------------------------------------------------------
// Element picking, the note card and the live style edits all live inside the page (`annotate.js`),
// because the page is a native webview and nothing in our DOM can be drawn on top of it. The app
// arms it and pulls the results back out; the page can never call in.

/** Arm or disarm element picking on the active page. */
export async function browserAnnotate(label: string, on: boolean): Promise<void> {
  if (inTauri) await invoke("browser_annotate", { label, on });
}

export async function browserAnnotations(label: string, url: string): Promise<Annotation[]> {
  return inTauri ? invoke<Annotation[]>("browser_annotations", { label, url }) : [];
}

export async function browserAnnotationCount(label: string): Promise<number> {
  return inTauri ? invoke<number>("browser_annotation_count", { label }) : 0;
}

/** Drop the notes and undo the live style edits they described. */
export async function browserAnnotationsClear(label: string): Promise<void> {
  if (inTauri) await invoke("browser_annotations_clear", { label });
}

/** A document finished loading — the point at which a fresh annotator exists to re-arm. */
export async function onBrowserLoad(cb: (p: BrowserNav) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<BrowserNav>("browser-load", (e) => cb(e.payload));
}

/** The page navigated itself — a link, a redirect, a form post. The address bar follows this. */
export async function onBrowserNav(cb: (p: BrowserNav) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<BrowserNav>("browser-nav", (e) => cb(e.payload));
}

export async function onBrowserTitle(
  cb: (p: { label: string; title: string }) => void,
): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<{ label: string; title: string }>("browser-title", (e) => cb(e.payload));
}

/** `target="_blank"` / `window.open`, denied natively and reopened here as a tab. */
export async function onBrowserPopup(cb: (p: BrowserNav) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<BrowserNav>("browser-popup", (e) => cb(e.payload));
}

/**
 * Native yes/no dialog. `window.confirm` is a silent always-true stub in wry's WKWebView (no
 * JS-confirm delegate), which turns every "are you sure?" into "yes" — so anything destructive
 * must come through here instead.
 */
export async function confirmNative(message: string): Promise<boolean> {
  if (!inTauri) return window.confirm(message);
  try {
    const { confirm } = await import("@tauri-apps/plugin-dialog");
    return await confirm(message, { kind: "warning" });
  } catch (e) {
    // A missing capability must fail closed: "no" loses nothing, "yes" can destroy work.
    console.error("confirmNative:", e);
    return false;
  }
}

/** Hand a URL to the system's default browser. Outside Tauri, a plain new tab. */
export async function openExternal(url: string): Promise<void> {
  if (inTauri) {
    const { open } = await import("@tauri-apps/plugin-shell");
    await open(url);
  } else {
    window.open(url, "_blank", "noopener");
  }
}

// ---- LSP bridge --------------------------------------------------------------------------------
// The Rust side spawns real language servers (rust-analyzer, pyright, gopls, …) as children and
// frames their stdio JSON-RPC; the frontend LSP client in src/lsp speaks the protocol. One server
// per (binary, project) pair — the key names that pair.

/** Spawn (or reuse) a language server for `lang` rooted at `cwd`. Null when none is installed. */
export async function lspStart(cwd: string, lang: string): Promise<string | null> {
  return inTauri ? invoke<string | null>("lsp_start", { cwd, lang }) : null;
}

/** Send one raw JSON-RPC message (already serialized) to the server behind `key`. */
export async function lspSend(key: string, payload: string): Promise<void> {
  if (inTauri) await invoke("lsp_send", { key, payload });
}

export interface LspMessage {
  key: string;
  payload: string;
}

export async function onLspMessage(cb: (p: LspMessage) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<LspMessage>("lsp-message", (e) => cb(e.payload));
}

/** The server process died or closed its pipe — the client for `key` is gone. */
export async function onLspExit(cb: (key: string) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<string>("lsp-exit", (e) => cb(e.payload));
}

/** Newest text per session id, for the rail's preview line. */
export async function sessionPreviews(): Promise<Record<string, string>> {
  if (!inTauri) return {};
  const rows = await invoke<[string, string][]>("session_previews");
  return Object.fromEntries(rows);
}

export interface SessionSearchHit {
  session_id: string;
  title: string;
  cwd: string;
  archived: boolean;
  role: "user" | "agent";
  snippet: string;
  seq: number;
}

/** Bounded full-text search over canonical user prompts and agent output. */
export async function searchSessions(query: string, limit = 12): Promise<SessionSearchHit[]> {
  return inTauri ? invoke<SessionSearchHit[]>("search_sessions", { query, limit }) : [];
}

// ---- projects ----------------------------------------------------------------------------------

export async function listProjects(): Promise<Project[]> {
  return inTauri ? invoke<Project[]>("list_projects") : [];
}

/**
 * Native folder chooser. Returns null when the user cancels — which is a normal outcome, not an
 * error. Outside Tauri there's no picker, so it resolves to null and the caller does nothing.
 */
export async function pickDirectory(): Promise<string | null> {
  if (!inTauri) return null;
  const { open } = await import("@tauri-apps/plugin-dialog");
  const picked = await open({ directory: true, multiple: false, title: "Choose a project folder" });
  return typeof picked === "string" ? picked : null;
}

/** Returns the resolved absolute path, which is the project's identity. */
export async function addProject(path: string, name?: string): Promise<string> {
  return inTauri ? invoke<string>("add_project", { path, name: name ?? null }) : path;
}

export async function openProject(path: string): Promise<void> {
  if (inTauri) await invoke("open_project", { path });
}

export async function renameProject(path: string, name: string): Promise<void> {
  if (inTauri) await invoke("rename_project", { path, name });
}

export async function setProjectWorktreeMode(
  path: string,
  mode: ProjectWorktreeMode | null,
): Promise<void> {
  if (inTauri) await invoke("set_project_worktree_mode", { path, mode });
}

export async function removeProject(path: string): Promise<void> {
  if (inTauri) await invoke("remove_project", { path });
}

/** Where a new session should start. Resolved by the core, never `"."` — see `default_cwd`. */
export async function defaultCwd(): Promise<string> {
  return inTauri ? invoke<string>("default_cwd") : ".";
}

export async function setModel(session: string, model: string): Promise<void> {
  if (inTauri) await invoke("set_model", { session, model });
}

/** Set an agent-reported config option (model, reasoning effort, …) by its id. */
export async function setConfigOption(session: string, configId: string, value: string): Promise<void> {
  if (inTauri) await invoke("set_config_option", { session, configId, value });
}

export async function cancelTurn(session: string): Promise<void> {
  if (inTauri) await invoke("cancel_turn", { session });
}

/**
 * Attach to the terminal `id`, creating it if it doesn't exist. Terminals live in the core, so a
 * re-attach returns `restore`: a VT dump to replay into a fresh renderer so the screen and
 * scrollback come back exactly as they were.
 */
export async function ptySpawn(
  id: string,
  cwd: string | null,
  rows: number,
  cols: number,
  opts?: { tmuxSession?: string | null; scrollback?: number },
): Promise<PtyAttach> {
  if (!inTauri) return { created: true, restore: "" };
  return invoke<PtyAttach>("pty_spawn", {
    id,
    cwd,
    rows,
    cols,
    scrollback: opts?.scrollback ?? null,
    tmuxSession: opts?.tmuxSession ?? null,
  });
}

export async function tmuxAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("tmux_available") : false;
}

export async function ptyWrite(id: string, data: string): Promise<void> {
  if (inTauri) await invoke("pty_write", { id, data });
}

export async function ptyResize(id: string, rows: number, cols: number): Promise<void> {
  if (inTauri) await invoke("pty_resize", { id, rows, cols });
}

/** Terminal contents as plain text — `all` includes scrollback, otherwise just the visible screen. */
export async function ptyDump(id: string, all = true): Promise<string> {
  return inTauri ? invoke<string>("pty_dump", { id, all }) : "";
}

/** Close a terminal for good, killing its child process. Detaching a renderer does not do this. */
export async function ptyKill(id: string): Promise<void> {
  if (inTauri) await invoke("pty_kill", { id });
}

export async function getTranscriptPage(
  session: string,
  before: number | null = null,
  limit = 20,
): Promise<TranscriptPage> {
  return inTauri
    ? invoke<TranscriptPage>("get_transcript_page", { session, before, limit })
    : { entries: [], next_before: null, snapshot_through: null };
}

// ---- git (F1) --------------------------------------------------------------------------------

export interface GitFile {
  path: string;
  original_path: string | null;
  staged: boolean;
  unstaged: boolean;
  state: string;
  staged_state: string | null;
  unstaged_state: string | null;
}
export interface GitStatus {
  is_repo: boolean;
  branch: string;
  ahead: number;
  behind: number;
  files: GitFile[];
}

export type SourceControlProviderKind =
  | "github"
  | "gitlab"
  | "azure-devops"
  | "bitbucket"
  | "unknown";

export interface SourceControlInfo {
  remote_name: string;
  provider: SourceControlProviderKind;
  provider_name: string;
  host: string;
  web_url: string | null;
  change_request_label: "PR" | "MR" | "change request";
  create_change_request_supported: boolean;
  required_cli: string | null;
  required_cli_available: boolean;
}

export async function gitSourceControlInfo(cwd: string): Promise<SourceControlInfo | null> {
  return inTauri ? invoke<SourceControlInfo | null>("git_source_control_info", { cwd }) : null;
}

export async function gitStatus(cwd: string): Promise<GitStatus> {
  return inTauri
    ? invoke<GitStatus>("git_status", { cwd })
    : { is_repo: false, branch: "", ahead: 0, behind: 0, files: [] };
}

export interface Checkpoint {
  id: string;
  refname: string;
  commit: string;
  message: string;
}

export async function gitCheckpoint(cwd: string, message: string): Promise<Checkpoint | null> {
  return inTauri ? invoke<Checkpoint>("git_checkpoint", { cwd, message }) : null;
}
export async function gitCheckpoints(cwd: string): Promise<Checkpoint[]> {
  return inTauri ? invoke<Checkpoint[]>("git_checkpoints", { cwd }) : [];
}

export type GitDiffScope = "all" | "staged" | "unstaged";

export interface GitDiffResult {
  text: string;
  truncated: boolean;
  truncation_reason: string | null;
  returned_bytes: number;
  files: number;
}

export interface GitDiffStat {
  added: number;
  deleted: number;
  files: number;
  truncated: boolean;
  truncation_reason: string | null;
}

const EMPTY_DIFF: GitDiffResult = {
  text: "",
  truncated: false,
  truncation_reason: null,
  returned_bytes: 0,
  files: 0,
};

export async function gitDiff(
  cwd: string,
  path: string | null,
  scope: GitDiffScope = "all",
): Promise<GitDiffResult> {
  return inTauri ? invoke<GitDiffResult>("git_diff", { cwd, path, scope }) : EMPTY_DIFF;
}
export async function gitDiffSince(cwd: string, commit: string): Promise<GitDiffResult> {
  return inTauri
    ? invoke<GitDiffResult>("git_diff_since", { cwd, commit })
    : EMPTY_DIFF;
}
export async function gitDiffStat(cwd: string): Promise<GitDiffStat> {
  return inTauri
    ? invoke<GitDiffStat>("git_diff_stat", { cwd })
    : { added: 0, deleted: 0, files: 0, truncated: false, truncation_reason: null };
}
export async function gitStagePaths(cwd: string, paths: string[]): Promise<void> {
  if (inTauri) await invoke("git_stage_paths", { cwd, paths });
}
export async function gitUnstagePaths(cwd: string, paths: string[]): Promise<void> {
  if (inTauri) await invoke("git_unstage_paths", { cwd, paths });
}
export async function gitRevert(cwd: string, commit: string): Promise<void> {
  if (inTauri) await invoke("git_revert", { cwd, commit });
}
export async function gitCommit(cwd: string, message: string): Promise<string> {
  return inTauri ? invoke<string>("git_commit", { cwd, message }) : "";
}
export async function gitPush(cwd: string): Promise<string> {
  return inTauri ? invoke<string>("git_push", { cwd }) : "";
}

// ---- keybindings (F2) ------------------------------------------------------------------------

export type KeymapEntry = [action: string, key: string, label: string];

// Mirrors `Action::default_key()` in crates/core/src/keymap.rs — keep the two in step. This is only
// the browser-preview fallback; inside Tauri the real keymap (with user overrides) comes from core.
export const DEFAULT_KEYMAP: KeymapEntry[] = [
  ["run", "Mod+Enter", "Run prompt"],
  ["new_session", "Mod+N", "New session"],
  ["cancel", "Mod+.", "Cancel turn"],
  ["toggle_terminal", "Mod+J", "Toggle terminal"],
  ["toggle_browser", "Mod+B", "Toggle browser"],
  ["toggle_git", "Mod+Shift+B", "Toggle git panel"],
  ["close_panel", "Escape", "Close side panel"],
  ["open_skill_picker", "Mod+/", "Open skill picker"],
  ["focus_editor", "Mod+E", "Focus editor"],
  ["toggle_doc_mode", "Mod+Shift+E", "Expand document to full height"],
  ["open_command_palette", "Mod+K", "Command palette"],
  ["open_source_control", "Mod+Shift+G", "Source control"],
  ["open_market", "Mod+Shift+M", "Open Plugin Hub"],
  ["open_files", "Mod+P", "Browse workspace files"],
  ["search_workspace", "Mod+Shift+F", "Search workspace contents"],
  ["open_issues", "Mod+Shift+I", "Open issues"],
  ["open_usage", "Mod+Shift+U", "Open usage"],
  ["open_settings", "Mod+,", "Open settings"],
  ["cycle_permission_mode", "Mod+Shift+P", "Cycle permission mode"],
  ["refresh_git", "Mod+G", "Refresh git status"],
  ["prev_session", "Mod+Alt+ArrowUp", "Previous session"],
  ["next_session", "Mod+Alt+ArrowDown", "Next session"],
  ["open_mission_control", "Mod+Shift+O", "Open mission control"],
];

export async function getKeymap(): Promise<KeymapEntry[]> {
  return inTauri ? invoke<KeymapEntry[]>("get_keymap") : DEFAULT_KEYMAP;
}

export async function setKeymap(action: string, key: string): Promise<void> {
  if (inTauri) await invoke("set_keymap", { action, key });
}

// ---- browser annotate (F3/F4) ----------------------------------------------------------------

/** One property the in-page annotator adjusted, and what it went from and to. */
export interface StyleChange {
  property: string;
  from: string;
  to: string;
}

export interface Annotation {
  url: string;
  note: string;
  selector: string | null;
  selected_text: string | null;
  styles: StyleChange[];
}

// ---- Plugin Hub + component market (F5) -------------------------------------------------------

export interface MarketItem {
  id: string;
  name: string;
  description: string;
  author: string;
  tags: string[];
  icon: string | null;
  kind: string;
  installed: boolean;
}

const FALLBACK_MARKET: MarketItem[] = [
  { id: "architect", name: "System Architect", description: "Design before coding.", author: "codetwo", tags: ["design"], icon: "🏛️", kind: "fragment", installed: false },
  { id: "test-suite", name: "Test Suite Author", description: "Thorough deterministic tests.", author: "codetwo", tags: ["testing"], icon: "🧪", kind: "fragment", installed: false },
  { id: "browser-tool", name: "Browser Tool (MCP)", description: "Give the agent a browser.", author: "codetwo", tags: ["mcp", "browser"], icon: "🌐", kind: "mcp", installed: false },
];

export async function marketCatalog(): Promise<MarketItem[]> {
  return inTauri ? invoke<MarketItem[]>("market_catalog") : FALLBACK_MARKET;
}

export async function marketInstall(id: string): Promise<void> {
  if (inTauri) await invoke("market_install", { id });
}

export interface PluginCounts {
  skills: number;
  subagents: number;
  mcp_servers: number;
  scaffolds: number;
  commands: number;
  hooks: number;
  lsp_servers: number;
  monitors: number;
  apps: number;
  /** Agent Scenes components (R14); serde-defaulted server-side, so always present here. */
  scenes: number;
  pipelines: number;
}

export type PluginStandard = "agent_plugins" | "codex" | "claude_code" | "conventional";
export type PluginInstallScope = "user" | "project" | "local" | "managed";

export interface PluginDiagnostic {
  level: "warning" | "error";
  code: string;
  message: string;
  component?: string;
}

export interface PluginExtensionComponent {
  kind: string;
  name: string;
  path: string;
  status: "ready" | "requires_trust" | "requires_auth" | "unsupported";
}

export interface PluginScaffoldInfo {
  id: string;
  name: string;
  description: string;
  files: number;
}

export interface PluginInfo {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  source: string;
  repository: string;
  spec_version: string;
  standard: PluginStandard;
  standards: PluginStandard[];
  enabled: boolean;
  trusted: boolean;
  scope: PluginInstallScope;
  counts: PluginCounts;
  scaffolds: PluginScaffoldInfo[];
  extension_components: PluginExtensionComponent[];
  diagnostics: PluginDiagnostic[];
}

export interface GitHubImportResult {
  plugin: PluginInfo;
}

export type MarketplacePluginSource =
  | { kind: "local"; path: string }
  | {
      kind: "github";
      repository: string;
      reference: string | null;
      sha: string | null;
    }
  | {
      kind: "git";
      url: string;
      path: string | null;
      reference: string | null;
      sha: string | null;
    }
  | {
      kind: "npm";
      package: string;
      version: string | null;
      registry: string | null;
    }
  | { kind: "archive"; url: string; sha256: string | null }
  | { kind: "unsupported"; description: string };

export interface MarketplacePlugin {
  name: string;
  display_name: string;
  description: string;
  version: string;
  category: string;
  installation_policy: string;
  authentication_policy: string;
  default_enabled: boolean;
  source: MarketplacePluginSource;
  installable: boolean;
  diagnostic: string | null;
}

export interface MarketplaceDiagnostic {
  code: string;
  message: string;
  entry: number | null;
}

export interface PluginMarketplace {
  name: string;
  display_name: string;
  description: string;
  manifest_path: string;
  root: string;
  standard: "codex" | "claude_code";
  plugins: MarketplacePlugin[];
  diagnostics: MarketplaceDiagnostic[];
}

const BROWSER_PLUGIN_MARKETPLACE: PluginMarketplace = {
  name: "code2-demo-marketplace",
  display_name: "Code2 compatibility preview",
  description: "A browser-only preview of marketplace source support and compatibility diagnostics.",
  manifest_path: "/demo/.claude-plugin/marketplace.json",
  root: "/demo",
  standard: "claude_code",
  plugins: [
    {
      name: "local-review-suite",
      display_name: "Local Review Suite",
      description: "A local plugin bundle that can be installed by the desktop runtime.",
      version: "2.1.0",
      category: "development",
      installation_policy: "allowed",
      authentication_policy: "none",
      default_enabled: true,
      source: { kind: "local", path: "./plugins/local-review-suite" },
      installable: true,
      diagnostic: null,
    },
    {
      name: "npm-observability-demo",
      display_name: "NPM Observability Demo",
      description: "Shown for compatibility visibility; the npm source adapter is not implemented yet.",
      version: "0.8.0",
      category: "monitoring",
      installation_policy: "allowed",
      authentication_policy: "none",
      default_enabled: false,
      source: {
        kind: "npm",
        package: "@example/observability-plugin",
        version: "0.8.0",
        registry: null,
      },
      installable: false,
      diagnostic: "npm marketplace sources are recognized but not installable in this release",
    },
  ],
  diagnostics: [],
};

export interface ScaffoldInstallResult {
  plugin: string;
  scaffold: string;
  destination: string;
  files: number;
}

export async function listPlugins(): Promise<PluginInfo[]> {
  return inTauri
    ? invoke<PluginInfo[]>("list_plugins")
    : [
        {
          id: "developer-toolkit-demo",
          name: "Developer Toolkit",
          version: "1.4.0",
          description: "A complete development workflow with review, research, tools, and starter projects.",
          author: "Code2 Community",
          source: "GitHub · example/developer-toolkit",
          repository: "https://github.com/example/developer-toolkit",
          spec_version: "1.0.0",
          standard: "agent_plugins",
          standards: ["agent_plugins", "codex", "claude_code"],
          enabled: true,
          trusted: false,
          scope: "user",
          counts: {
            skills: 1,
            subagents: 1,
            mcp_servers: 1,
            scaffolds: 1,
            commands: 1,
            hooks: 1,
            lsp_servers: 1,
            monitors: 0,
            apps: 0,
            scenes: 1,
            pipelines: 1,
          },
          extension_components: [
            {
              kind: "lsp",
              name: "rust",
              path: ".lsp.json",
              status: "requires_trust",
            },
            {
              kind: "hook",
              name: "session",
              path: "hooks/hooks.json",
              status: "unsupported",
            },
          ],
          diagnostics: [],
          scaffolds: [
            {
              id: "vite-react-demo",
              name: "Vite React app",
              description: "TypeScript, tests, and a production-ready project structure",
              files: 12,
            },
          ],
        },
      ];
}

/** Install a complete plugin from a GitHub repository or a selected /tree/ path. */
export async function githubImportPlugin(repository: string): Promise<GitHubImportResult> {
  if (!inTauri) throw new Error("Plugin installation requires the Code2 desktop app.");
  return invoke<GitHubImportResult>("github_import_plugin", { repository });
}

export async function pickPluginMarketplace(): Promise<PluginMarketplace | null> {
  if (!inTauri) return BROWSER_PLUGIN_MARKETPLACE;
  const { open } = await import("@tauri-apps/plugin-dialog");
  const selected = await open({
    multiple: false,
    directory: false,
    filters: [{ name: "Plugin marketplace", extensions: ["json"] }],
  });
  if (typeof selected !== "string") return null;
  return invoke<PluginMarketplace>("read_plugin_marketplace", {
    path: selected,
  });
}

export async function installMarketplacePlugin(
  marketplacePath: string,
  pluginName: string,
): Promise<GitHubImportResult> {
  if (!inTauri) throw new Error("Marketplace installation requires the Code2 desktop app.");
  return invoke<GitHubImportResult>("install_marketplace_plugin", {
    marketplacePath,
    pluginName,
  });
}

export async function uninstallPlugin(id: string, keepData = false): Promise<void> {
  if (inTauri) await invoke("uninstall_plugin", { id, keepData });
}

export async function setPluginEnabled(id: string, enabled: boolean): Promise<PluginInfo> {
  if (!inTauri) throw new Error("Plugin state changes require the Code2 desktop app.");
  return invoke<PluginInfo>("set_plugin_enabled", { id, enabled });
}

export async function setPluginTrusted(id: string, trusted: boolean): Promise<PluginInfo> {
  if (!inTauri) throw new Error("Plugin trust changes require the Code2 desktop app.");
  return invoke<PluginInfo>("set_plugin_trusted", { id, trusted });
}

export async function applyPluginScaffold(
  pluginId: string,
  scaffoldId: string,
  cwd: string,
): Promise<ScaffoldInstallResult> {
  if (!inTauri) throw new Error("Scaffold installation requires the Code2 desktop app.");
  return invoke<ScaffoldInstallResult>("apply_plugin_scaffold", { pluginId, scaffoldId, cwd });
}

// ---- remote control (F10) --------------------------------------------------------------------

export interface RemoteEndpoint {
  id: string;
  label: string;
  url: string;
  /** Loopback remains copyable for this Mac, but must never be encoded for another device. */
  qr_shareable: boolean;
}

export interface RemoteStatus {
  port: number;
  endpoints: RemoteEndpoint[];
}

export interface RemotePairingLink {
  endpoint_id: string;
  url: string;
  token: string;
  expires_in: number;
  qr_svg: string;
}

export interface RemoteDevice {
  id: string;
  name: string;
  created_at: number;
  last_seen: number;
}

/** Turn on network access: serve the live engine on all interfaces (idempotent). */
export async function startRemote(port?: number): Promise<RemoteStatus | null> {
  return inTauri ? invoke<RemoteStatus>("start_remote", { port: port ?? null }) : null;
}

/** Turn off network access. Paired devices persist and reconnect next time. */
export async function stopRemote(): Promise<void> {
  if (inTauri) await invoke("stop_remote");
}

export async function remoteStatus(): Promise<RemoteStatus | null> {
  return inTauri ? invoke<RemoteStatus | null>("remote_status") : null;
}

/** Mint a fresh one-time pairing link for an advertised endpoint (URL + optional QR SVG). */
export async function remotePairingLink(
  endpointId?: string,
  ttlSecs?: number,
): Promise<RemotePairingLink | null> {
  return inTauri
    ? invoke<RemotePairingLink>("remote_pairing_link", {
        endpointId: endpointId ?? null,
        ttlSecs: ttlSecs ?? null,
      })
    : null;
}

export async function remoteDevices(): Promise<RemoteDevice[]> {
  return inTauri ? invoke<RemoteDevice[]>("remote_devices") : [];
}

export async function remoteRevokeDevice(id: string): Promise<boolean> {
  return inTauri ? invoke<boolean>("remote_revoke_device", { id }) : false;
}

// ---- issues (F14) ----------------------------------------------------------------------------

export interface Issue {
  id: string;
  title: string;
  state: string;
  url: string;
  body: string;
  source: string;
}

export async function ghAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("gh_available") : false;
}
export async function listGithubIssues(cwd: string, limit = 30): Promise<Issue[]> {
  return inTauri ? invoke<Issue[]>("list_github_issues", { cwd, limit }) : [];
}
export async function listLinearIssues(token: string, limit = 30): Promise<Issue[]> {
  return inTauri ? invoke<Issue[]>("list_linear_issues", { token, limit }) : [];
}
export async function issueContext(issue: Issue): Promise<string> {
  if (inTauri) return invoke<string>("issue_context", { issue });
  return `**${issue.source} #${issue.id}** — ${issue.title} (${issue.state})\n${issue.url}`;
}

// ---- compiled-prompt preview (F13) -----------------------------------------------------------

export type CanvasPixelPolicy = "required" | "structure_only";
export type CanvasTheme = "light" | "dark";
export type CanvasObjectKind =
  | "pen"
  | "text"
  | "rectangle"
  | "ellipse"
  | "line"
  | "arrow"
  | "image";

export interface CanvasFeatureState {
  feature: string;
  enabled: boolean;
  status: "not production-enabled";
}

export interface CanvasPoint {
  x: number;
  y: number;
}

export interface CanvasRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface CanvasObject {
  id: string;
  kind: CanvasObjectKind;
  originalText?: string;
  bounds: CanvasRect;
  layer: number;
  arrowStart?: CanvasPoint | null;
  arrowEnd?: CanvasPoint | null;
  assetId?: string | null;
}

export interface CanvasAssetRef {
  id: string;
  mimeType: "image/png" | "image/webp";
  width: number;
  height: number;
  sourceName?: string | null;
}

export interface CanvasStaticAsset extends CanvasAssetRef {
  bytes: number[];
}

export interface CanvasSceneEnvelope {
  engine: string;
  engineVersion: string;
  schemaVersion: number;
  revision: number;
  theme: CanvasTheme;
  assets: CanvasAssetRef[];
  /** Exact opaque Excalidraw scene retained by the core; no active refs are accepted on write. */
  scene: Record<string, unknown>;
}

export interface CanvasManifest {
  objects: CanvasObject[];
}

export type CanvasExportKind = "overview" | "detail";
export interface CanvasExport {
  id: string;
  kind: CanvasExportKind;
  index?: number | null;
  mimeType: "image/png";
  width: number;
  height: number;
  bytes: number[];
}

export interface CanvasDraftUpdate {
  title: string;
  theme: CanvasTheme;
  envelope: CanvasSceneEnvelope;
  manifest: CanvasManifest;
  assets?: CanvasStaticAsset[];
}

export interface CanvasFreezeInput extends CanvasDraftUpdate {
  exports?: CanvasExport[];
}

export interface CanvasDraft {
  id: string;
  owner: string;
  revision: number;
  title: string;
  theme: CanvasTheme;
  envelope: CanvasSceneEnvelope;
  manifest: CanvasManifest;
  assets: CanvasStaticAsset[];
  createdAt: number;
  updatedAt: number;
  tombstonedAt?: number | null;
}

/** Immutable history wire shape. Mutable owner/head timestamps are intentionally absent. */
export interface CanvasSnapshot {
  id: string;
  revision: number;
  title: string;
  theme: CanvasTheme;
  envelope: CanvasSceneEnvelope;
  manifest: CanvasManifest;
  assets: CanvasStaticAsset[];
  createdAt: number;
  frozenAt: number;
  objectCount: number;
  summary: string;
  exports: CanvasExport[];
}

export function canvasFeatureState(): Promise<CanvasFeatureState> {
  return inTauri
    ? invoke<CanvasFeatureState>("canvas_feature_state")
    : Promise.resolve({
        feature: "CODETWO_CANVAS_INPUT_V1",
        enabled: false,
        status: "not production-enabled",
      });
}

function canvasAssetToCore(asset: CanvasStaticAsset): Record<string, unknown> {
  return {
    id: asset.id,
    mime_type: asset.mimeType,
    width: asset.width,
    height: asset.height,
    bytes: asset.bytes,
  };
}

function canvasEnvelopeToCore(envelope: CanvasSceneEnvelope): Record<string, unknown> {
  return {
    engine: envelope.engine,
    engine_version: envelope.engineVersion,
    schema_version: envelope.schemaVersion,
    revision: envelope.revision,
    theme: envelope.theme,
    assets: envelope.assets.map((asset) => ({
      id: asset.id,
      mime_type: asset.mimeType,
      width: asset.width,
      height: asset.height,
      source_name: asset.sourceName ?? null,
    })),
    scene: envelope.scene,
  };
}

function canvasManifestToCore(manifest: CanvasManifest): Record<string, unknown> {
  return {
    objects: manifest.objects.map((object) => ({
      id: object.id,
      kind: object.kind,
      original_text: object.originalText ?? "",
      bounds: object.bounds,
      layer: object.layer,
      arrow_start: object.arrowStart ?? null,
      arrow_end: object.arrowEnd ?? null,
      asset_id: object.assetId ?? null,
    })),
  };
}

function canvasExportToCore(exportItem: CanvasExport): Record<string, unknown> {
  return {
    id: exportItem.id,
    kind: exportItem.kind,
    index: exportItem.index ?? null,
    mime_type: exportItem.mimeType,
    width: exportItem.width,
    height: exportItem.height,
    bytes: exportItem.bytes,
  };
}

function canvasUpdateToCore(update: CanvasDraftUpdate): Record<string, unknown> {
  return {
    title: update.title,
    theme: update.theme,
    envelope: canvasEnvelopeToCore(update.envelope),
    manifest: canvasManifestToCore(update.manifest),
    assets: (update.assets ?? []).map(canvasAssetToCore),
  };
}

function canvasFreezeToCore(input: CanvasFreezeInput): Record<string, unknown> {
  return {
    ...canvasUpdateToCore(input),
    exports: (input.exports ?? []).map(canvasExportToCore),
  };
}

export async function canvasCreateDraft(title: string): Promise<CanvasDraft> {
  return invoke<CanvasDraft>("canvas_create_draft", { title });
}

export async function canvasGetDraft(id: string): Promise<CanvasDraft | null> {
  return invoke<CanvasDraft | null>("canvas_get_draft", { id });
}

export async function canvasUpdateDraft(
  id: string,
  expectedRevision: number,
  update: CanvasDraftUpdate,
): Promise<CanvasDraft> {
  return invoke<CanvasDraft>("canvas_update_draft", {
    id,
    expectedRevision,
    update: canvasUpdateToCore(update),
  });
}

export async function canvasNormalizeMedia(
  bytes: Uint8Array | number[],
  declaredMime?: string | null,
): Promise<CanvasStaticAsset> {
  return invoke<CanvasStaticAsset>("canvas_normalize_media", {
    bytes: Array.from(bytes),
    declaredMime: declaredMime ?? null,
  });
}

export async function canvasFreeze(
  id: string,
  expectedRevision: number,
  input: CanvasFreezeInput,
): Promise<CanvasSnapshot> {
  return invoke<CanvasSnapshot>("canvas_freeze", {
    id,
    expectedRevision,
    input: canvasFreezeToCore(input),
  });
}

export async function canvasGetSnapshot(id: string, revision: number): Promise<CanvasSnapshot | null> {
  return invoke<CanvasSnapshot | null>("canvas_get_snapshot", { id, revision });
}

export async function canvasGetAsset(
  id: string,
  revision: number,
  assetId: string,
): Promise<CanvasStaticAsset | null> {
  return invoke<CanvasStaticAsset | null>("canvas_get_asset", { id, revision, assetId });
}

export async function canvasGetExport(
  id: string,
  revision: number,
  exportId: string,
): Promise<CanvasExport | null> {
  return invoke<CanvasExport | null>("canvas_get_export", { id, revision, exportId });
}

export async function canvasDuplicate(id: string, revision: number): Promise<CanvasDraft> {
  return invoke<CanvasDraft>("canvas_duplicate", { id, revision });
}

export async function canvasTombstone(id: string): Promise<void> {
  return invoke("canvas_tombstone", { id });
}

export async function canvasRestore(id: string): Promise<void> {
  return invoke("canvas_restore", { id });
}

export async function canvasPurge(id: string): Promise<boolean> {
  return invoke<boolean>("canvas_purge", { id });
}

export interface CompiledPreview {
  prompt: string;
  mcp_servers: string[];
  agent_skills: string[];
  subagents: string[];
  files: string[];
  images: string[];
  sessions: string[];
  unresolved: string[];
  canvases: CompiledCanvasPreview[];
}

export interface CompiledCanvasPreview {
  id: string;
  frozenRevision: number;
  title: string;
  summary: string;
  /** Ordered overview first, then detail tiles as returned by core validation. */
  exports: CanvasExport[];
}

export async function compileDoc(doc: DocBlock[], cwd?: string | null): Promise<CompiledPreview> {
  if (inTauri) return invoke<CompiledPreview>("compile_doc", { doc, cwd: cwd ?? null });
  return {
    prompt: doc.map(describeBlock).join("\n\n"),
    mcp_servers: [],
    agent_skills: [],
    subagents: [],
    files: doc.flatMap((b) => (b.type === "file" ? [b.path] : [])),
    images: doc.flatMap((b) => (b.type === "image" ? [b.path] : [])),
    sessions: doc.flatMap((b) => (b.type === "session" ? [b.session_id] : [])),
    unresolved: [],
    canvases: [],
  };
}

// ---- sandbox + project scripts (G7/G8) ---------------------------------------------------------

export async function setSandbox(session: string, sandbox: Sandbox): Promise<void> {
  if (inTauri) await invoke("set_sandbox", { session, sandbox });
}

export interface ProjectScript {
  id: string;
  name: string;
  command: string;
  run_on_worktree_create: boolean;
}

export async function listProjectScripts(cwd: string): Promise<ProjectScript[]> {
  return inTauri ? invoke<ProjectScript[]>("list_project_scripts", { cwd }) : [];
}

export async function runProjectScript(cwd: string, id: string): Promise<string> {
  return inTauri ? invoke<string>("run_project_script", { cwd, id }) : "";
}

// ---- voice input (G11) -------------------------------------------------------------------------

/// Whether the core has a local transcriber configured (CODETWO_TRANSCRIBE_CMD or an auto-detected
/// whisper binary). The UI prefers the webview's own speech recognition when present.
export async function voiceAvailable(): Promise<boolean> {
  return inTauri ? invoke<boolean>("voice_available") : false;
}

export async function transcribeAudio(bytes: Uint8Array, ext = "webm"): Promise<string> {
  if (!inTauri) return "";
  return invoke<string>("transcribe_audio", { bytes: Array.from(bytes), ext });
}

// ---- usage tracking (G12) ----------------------------------------------------------------------

export interface UsageWindow {
  label: string;
  window_secs: number;
  input_tokens: number;
  /// Cache reads — reported but excluded from `total_tokens`.
  cached_tokens: number;
  output_tokens: number;
  total_tokens: number;
  limit: number | null;
  fraction: number | null;
  resets_in_secs: number;
}

export interface UsageReport {
  windows: UsageWindow[];
  by_source: [string, number][];
  transcripts: number;
}

const EMPTY_USAGE: UsageReport = {
  windows: [
    { label: "5h session", window_secs: 18000, input_tokens: 0, cached_tokens: 0, output_tokens: 0, total_tokens: 0, limit: null, fraction: null, resets_in_secs: 0 },
    { label: "week", window_secs: 604800, input_tokens: 0, cached_tokens: 0, output_tokens: 0, total_tokens: 0, limit: null, fraction: null, resets_in_secs: 0 },
    { label: "month", window_secs: 2592000, input_tokens: 0, cached_tokens: 0, output_tokens: 0, total_tokens: 0, limit: null, fraction: null, resets_in_secs: 0 },
  ],
  by_source: [],
  transcripts: 0,
};

export async function usageReport(): Promise<UsageReport> {
  return inTauri ? invoke<UsageReport>("usage_report") : EMPTY_USAGE;
}

// ---- workspace files & rules (G1/G2) ---------------------------------------------------------

const FALLBACK_FILES = ["src/main.rs", "src/lib.rs", "README.md"];

export async function listFiles(cwd: string, query: string, limit = 50): Promise<string[]> {
  if (!inTauri) return FALLBACK_FILES.filter((f) => f.includes(query));
  return invoke<string[]>("list_files", { cwd, query, limit });
}

export interface WorkspaceSearchOptions {
  regex: boolean;
  case_sensitive: boolean;
  whole_word: boolean;
}

export interface WorkspaceContentMatch {
  path: string;
  line: number;
  column: number;
  preview: string;
}

export interface WorkspaceSearchResult {
  matches: WorkspaceContentMatch[];
  truncated: boolean;
  truncation_reason: string | null;
}

export async function searchWorkspaceContents(
  cwd: string,
  query: string,
  options: WorkspaceSearchOptions,
  requestId: string,
  limit = 200,
): Promise<WorkspaceSearchResult> {
  if (!inTauri) return { matches: [], truncated: false, truncation_reason: null };
  return invoke<WorkspaceSearchResult>("search_workspace_contents", {
    cwd,
    query,
    options,
    limit,
    requestId,
  });
}

export async function cancelWorkspaceContentSearch(requestId: string): Promise<boolean> {
  return inTauri
    ? invoke<boolean>("cancel_workspace_content_search", { requestId })
    : false;
}

export async function listRules(cwd: string): Promise<string[]> {
  return inTauri ? invoke<string[]>("list_rules", { cwd }) : [];
}

// ---- session management (G5) -----------------------------------------------------------------

export async function renameSession(session: string, title: string): Promise<void> {
  if (inTauri) await invoke("rename_session", { session, title });
}
export async function archiveSession(session: string, archived: boolean): Promise<void> {
  if (inTauri) await invoke("archive_session", { session, archived });
}
export async function pinSession(session: string, pinned: boolean): Promise<void> {
  if (inTauri) await invoke("pin_session", { session, pinned });
}
export async function listArchivedSessions(): Promise<SessionInfo[]> {
  return inTauri ? invoke<SessionInfo[]>("list_archived_sessions") : [];
}

// ---- PR + commit message (G6) ------------------------------------------------------------------

export async function gitCreatePr(cwd: string, title: string, body: string): Promise<string> {
  return inTauri ? invoke<string>("git_create_pr", { cwd, title, body }) : "";
}
export async function gitSuggestCommit(cwd: string): Promise<string> {
  return inTauri ? invoke<string>("git_suggest_commit", { cwd }) : "chore: update";
}

export async function browserContext(annotation: Annotation): Promise<string> {
  if (inTauri) return invoke<string>("browser_context", { annotation });
  // Local fallback mirrors core::browser::Annotation::to_context.
  let s = `**Browser context** — ${annotation.url}`;
  if (annotation.selected_text) s += `\n- selected: “${annotation.selected_text}”`;
  if (annotation.note) s += `\n- note: ${annotation.note}`;
  return s;
}

export async function saveSkill(skill: Skill): Promise<void> {
  if (inTauri) await invoke("save_skill", { skill });
}

export async function deleteSkill(id: string): Promise<void> {
  if (inTauri) await invoke("delete_skill", { id });
}

export async function onEngineEvent(cb: (ev: CoreEvent) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<CoreEvent>("engine-event", (e) => cb(e.payload));
}

export async function onPtyOutput(cb: (p: PtyOutput) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<PtyOutput>("pty-output", (e) => cb(e.payload));
}

export async function onPtyTitle(cb: (p: PtyTitle) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<PtyTitle>("pty-title", (e) => cb(e.payload));
}

/** Fires when a terminal's child process exits. */
export async function onPtyExit(cb: (id: string) => void): Promise<() => void> {
  if (!inTauri) return () => {};
  return listen<string>("pty-exit", (e) => cb(e.payload));
}

export function providerLabel(p: string | { custom: string }): string {
  return typeof p === "string" ? p : p.custom;
}

// ---- scenes (Agent Scenes 1.0.0; see docs/scenes.md) ---------------------------------------

import type { SceneInfo } from "./session/scene";

export interface SceneEscalation {
  from: string;
  to: string;
}

export interface SceneApplyOutcome {
  applied: string[];
  pending: string[];
  escalation: SceneEscalation | null;
  plan_first: boolean | null;
  suppress_unpinned: boolean;
  pinned_skills: string[];
}

export interface SceneSessionParams {
  provider: string | null;
  model: string | null;
  reasoning_effort: string | null;
  use_worktree: boolean | null;
  worktree_base: WorktreeBaselineKind | null;
  initial_policy: { mode: PermissionMode; sandbox: Sandbox } | null;
}

export interface SceneSessionPlanOutcome {
  params: SceneSessionParams | null;
  escalation: SceneEscalation | null;
}

export interface SessionSceneState {
  reference: string;
  customized: boolean;
  resolved: boolean;
}

/// Every scene call degrades on a missing backend command (feature-detect: catch → fallback),
/// so a frontend running against an older core hides the affordance instead of breaking.
export async function listScenes(cwd?: string): Promise<SceneInfo[]> {
  if (!inTauri) return [];
  return invoke<SceneInfo[]>("list_scenes", { cwd: cwd ?? null }).catch(() => []);
}

export async function getScene(
  reference: string,
): Promise<{ reference: string; source: string; scene: unknown } | null> {
  if (!inTauri) return null;
  return invoke<{ reference: string; source: string; scene: unknown }>("get_scene", {
    reference,
  }).catch(() => null);
}

export async function applySceneToSession(
  session: string,
  reference: string,
  confirmEscalation: boolean,
): Promise<SceneApplyOutcome | null> {
  if (!inTauri) return null;
  return invoke<SceneApplyOutcome>("apply_scene", {
    session,
    reference,
    confirmEscalation,
  }).catch(() => null);
}

export async function sceneSessionPlan(
  reference: string,
  confirmEscalation: boolean,
): Promise<SceneSessionPlanOutcome | null> {
  if (!inTauri) return null;
  return invoke<SceneSessionPlanOutcome>("scene_session_plan", {
    reference,
    confirmEscalation,
  }).catch(() => null);
}

export async function setSessionScene(
  session: string,
  reference: string | null,
  customized: boolean,
): Promise<void> {
  if (!inTauri) return;
  await invoke("set_session_scene", { session, reference, customized }).catch(() => {});
}

export async function getSessionScene(session: string): Promise<SessionSceneState | null> {
  if (!inTauri) return null;
  return invoke<SessionSceneState | null>("get_session_scene", { session }).catch(() => null);
}

/** Diff stat of a session's own checkout, shaped for display. Null when unknown or not a repo. */
export interface SessionDiffStat {
  files: number;
  additions: number;
  deletions: number;
}

export async function sessionDiffStat(session: string): Promise<SessionDiffStat | null> {
  if (!inTauri) return null;
  return invoke<GitDiffStat | null>("session_diff_stat", { session })
    .then((stat) =>
      stat ? { files: stat.files, additions: stat.added, deletions: stat.deleted } : null,
    )
    .catch(() => null);
}

/** Per-session token/cost totals. The core command lands in a later wave — until then this
 * resolves null everywhere and the statusline's cost segment stays hidden (feature detect). */
export interface SessionUsage {
  input_tokens: number;
  output_tokens: number;
  cost_usd: number | null;
  burn_rate_usd_per_hour: number | null;
  priced: boolean;
}

export async function usageBySession(session: string): Promise<SessionUsage | null> {
  if (!inTauri) return null;
  return invoke<SessionUsage | null>("usage_by_session", { session }).catch(() => null);
}

// ---- scene artifacts (R4) -------------------------------------------------------------------

/** One captured version of one scene artifact, as `list_scene_artifacts` reports it. */
export interface SceneArtifactRecord {
  id: number;
  scene_ref: string;
  artifact_key: string;
  kind: string;
  title: string;
  session_id: string;
  pipeline_instance_id: string | null;
  stage_id: string | null;
  artifact: ArtifactRef;
  version: number;
  pinned: boolean;
  created_at: number;
}

/// Same degradation contract as the scene calls above: against an older core the commands are
/// missing and every call quietly reports "no artifacts" instead of breaking the surface.
export async function listSceneArtifacts(session: string): Promise<SceneArtifactRecord[]> {
  if (!inTauri) return [];
  return invoke<SceneArtifactRecord[]>("list_scene_artifacts", { session }).catch(() => []);
}

export async function sceneArtifactContent(recordId: number): Promise<string | null> {
  if (!inTauri) return null;
  return invoke<string>("scene_artifact_content", { recordId }).catch(() => null);
}

export async function recordSceneArtifact(
  session: string,
  artifactKey: string,
  content: string,
): Promise<SceneArtifactRecord | null> {
  if (!inTauri) return null;
  return invoke<SceneArtifactRecord>("record_scene_artifact", {
    session,
    artifactKey,
    content,
  }).catch(() => null);
}

export async function pinSceneArtifact(
  session: string,
  artifactKey: string,
  version: number | null,
): Promise<void> {
  if (!inTauri) return;
  await invoke("pin_scene_artifact", { session, artifactKey, version }).catch(() => {});
}

// ---- issue write path (R12) -----------------------------------------------------------------

/**
 * Post a delegation comment on a GitHub ("github") or Linear ("linear") issue; resolves to the
 * comment URL. Linear needs the caller-held API token (same source as `listLinearIssues`).
 * Null when unavailable: browser preview, older core, or the comment failed to post.
 */
export async function commentIssue(
  cwd: string,
  source: string,
  id: string,
  body: string,
  token?: string,
): Promise<string | null> {
  if (!inTauri) return null;
  return invoke<string>("comment_issue", { cwd, source, id, body, token: token ?? null }).catch(
    () => null,
  );
}

// ---- voice → structured brief (R11) --------------------------------------------------------

import type { SceneSlotDef } from "./session/scene";

/**
 * Heuristically distribute a finished dictation across a scene brief's slots (core-side keyword
 * sectioning; no model call). Null on browser preview, an older core, or any failure — the caller
 * must fall back to inserting the raw transcript so it is never lost.
 */
export async function structureBrief(
  transcript: string,
  slots: SceneSlotDef[],
): Promise<Record<string, string> | null> {
  if (!inTauri) return null;
  return invoke<Record<string, string>>("structure_brief", { transcript, slots }).catch(() => null);
}

// ---- template-from-history (R2) --------------------------------------------------------------

/** Heuristic `{{slot-N}}` proposal over a past prompt, as `propose_macro_slots` reports it. */
export interface ProposedMacro {
  template: string;
  slots: SceneSlotDef[];
}

/**
 * Null on browser preview or an older core (missing command) — the template dialog then opens as
 * a plain manual editor over the raw prompt instead of breaking.
 */
export async function proposeMacroSlots(text: string): Promise<ProposedMacro | null> {
  if (!inTauri) return null;
  return invoke<ProposedMacro>("propose_macro_slots", { text }).catch(() => null);
}

// ---- scene hooks (R8) -----------------------------------------------------------------------

/// Remember a completion-banner dismissal so the same exit state never re-fires this session.
export async function dismissSceneBanner(session: string, stateKey: string): Promise<void> {
  if (!inTauri) return;
  await invoke("dismiss_scene_banner", { session, stateKey }).catch(() => {});
}

/// Enable/disable scene `schedule` hooks for one project (off by default).
export async function setProjectScheduling(path: string, enabled: boolean): Promise<void> {
  if (!inTauri) return;
  await invoke("set_project_scheduling", { path, enabled }).catch(() => {});
}

// ---- pipeline instances (R9) ----------------------------------------------------------------

/** One resolved pipeline definition, as `list_pipelines` reports it. */
export interface PipelineInfo {
  reference: string;
  name: string;
  title: string;
  description: string;
  icon: string | null;
  source: string;
  stage_count: number;
}

/** One running (or finished) pipeline instance. */
export interface PipelineInstance {
  id: string;
  pipeline_ref: string;
  project_path: string;
  current_stage: string;
  status: string;
  created_at: number;
  updated_at: number;
}

export interface PipelineTransitionRecord {
  instance_id: string;
  seq: number;
  from_stage: string | null;
  to_stage: string;
  trigger: string;
  gate: string;
  session_id: string | null;
  created_at: number;
}

/** One stage on the horizontal stage track. */
export interface PipelineStageStatus {
  id: string;
  scene_ref: string;
  title: string;
  state: "done" | "current" | "pending";
  gate: string;
  loop_count: number;
  sessions: string[];
  artifacts: SceneArtifactRecord[];
}

export interface PipelineInstanceDetail {
  instance: PipelineInstance;
  transitions: PipelineTransitionRecord[];
  stages: PipelineStageStatus[];
}

export interface PipelineStartOutcome {
  detail: PipelineInstanceDetail;
  applied_scene: SceneApplyOutcome | null;
}

export interface PipelineAdvanceOutcome {
  instance: PipelineInstance;
  applied_scene: SceneApplyOutcome | null;
  session_plan: SceneSessionParams | null;
  escalation: SceneEscalation | null;
  carried: string[];
}

/// Same degradation contract as the other scene calls: on an older core every call quietly
/// reports "no pipelines" instead of breaking the surface.
export async function listPipelines(): Promise<PipelineInfo[]> {
  if (!inTauri) return [];
  return invoke<PipelineInfo[]>("list_pipelines", {}).catch(() => []);
}

export async function startPipeline(
  reference: string,
  projectPath: string,
  session: string | null,
): Promise<PipelineStartOutcome | null> {
  if (!inTauri) return null;
  return invoke<PipelineStartOutcome>("start_pipeline", {
    reference,
    projectPath,
    session,
  }).catch(() => null);
}

export async function advancePipeline(
  instanceId: string,
  toStage: string,
  session: string | null,
  confirm: boolean,
): Promise<PipelineAdvanceOutcome | null> {
  if (!inTauri) return null;
  return invoke<PipelineAdvanceOutcome>("advance_pipeline", {
    instanceId,
    toStage,
    session,
    confirm,
  }).catch(() => null);
}

export async function bindPipelineSession(
  instanceId: string,
  stageId: string,
  session: string,
): Promise<void> {
  if (!inTauri) return;
  await invoke("bind_pipeline_session", { instanceId, stageId, session }).catch(() => {});
}

export async function getPipelineInstance(
  instanceId: string,
): Promise<PipelineInstanceDetail | null> {
  if (!inTauri) return null;
  return invoke<PipelineInstanceDetail>("get_pipeline_instance", { instanceId }).catch(() => null);
}

export async function listPipelineInstances(projectPath: string): Promise<PipelineInstance[]> {
  if (!inTauri) return [];
  return invoke<PipelineInstance[]>("list_pipeline_instances", { projectPath }).catch(() => []);
}

/** The active session's pipeline binding — the stage track renders only when this is set. */
export async function sessionPipeline(
  session: string,
): Promise<{ instance_id: string; stage_id: string } | null> {
  if (!inTauri) return null;
  return invoke<{ instance_id: string; stage_id: string } | null>("session_pipeline", {
    session,
  }).catch(() => null);
}

// ---- issue delegation trail (R12 cleanup) ----------------------------------------------------

/** One "delegated to scene" event on an issue's accountability trail. */
export interface IssueDelegation {
  id: number;
  source: string;
  issue_id: string;
  issue_title: string;
  scene_ref: string;
  scene_title: string;
  session_id: string | null;
  comment_url: string | null;
  created_at: number;
}

export async function recordIssueDelegation(
  source: string,
  issueId: string,
  issueTitle: string,
  sceneRef: string,
  sceneTitle: string,
): Promise<number | null> {
  if (!inTauri) return null;
  return invoke<number>("record_issue_delegation", {
    source,
    issueId,
    issueTitle,
    sceneRef,
    sceneTitle,
  }).catch(() => null);
}

export async function setIssueDelegationSession(id: number, session: string): Promise<void> {
  if (!inTauri) return;
  await invoke("set_issue_delegation_session", { id, session }).catch(() => {});
}

export async function setIssueDelegationComment(id: number, url: string): Promise<void> {
  if (!inTauri) return;
  await invoke("set_issue_delegation_comment", { id, url }).catch(() => {});
}

export async function listIssueDelegations(
  source: string,
  issueId: string,
): Promise<IssueDelegation[]> {
  if (!inTauri) return [];
  return invoke<IssueDelegation[]>("list_issue_delegations", { source, issueId }).catch(() => []);
}

/** Whether scene `schedule` hooks are enabled for this project (off by default). */
export async function getProjectScheduling(path: string): Promise<boolean> {
  if (!inTauri) return false;
  return invoke<boolean>("get_project_scheduling", { path }).catch(() => false);
}

/** Lossy SKILL.md export of a scene (docs/scenes.md §Interop); null when it cannot resolve. */
export async function exportSceneSkillMd(reference: string): Promise<string | null> {
  if (!inTauri) return null;
  return invoke<string>("export_scene_skill_md", { reference }).catch(() => null);
}
