import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from "react";
import type { Icon as PhosphorIcon, IconProps as PhosphorIconProps } from "@phosphor-icons/react";
import { PulseIcon } from "@phosphor-icons/react/dist/csr/Pulse";
import { WarningCircleIcon } from "@phosphor-icons/react/dist/csr/WarningCircle";
import { WarningIcon } from "@phosphor-icons/react/dist/csr/Warning";
import { ArchiveIcon } from "@phosphor-icons/react/dist/csr/Archive";
import { TrayArrowUpIcon } from "@phosphor-icons/react/dist/csr/TrayArrowUp";
import { TrayArrowDownIcon } from "@phosphor-icons/react/dist/csr/TrayArrowDown";
import { ArrowDownIcon } from "@phosphor-icons/react/dist/csr/ArrowDown";
import { ArrowLeftIcon } from "@phosphor-icons/react/dist/csr/ArrowLeft";
import { ArrowRightIcon } from "@phosphor-icons/react/dist/csr/ArrowRight";
import { ArrowUpIcon } from "@phosphor-icons/react/dist/csr/ArrowUp";
import { ArrowUpRightIcon } from "@phosphor-icons/react/dist/csr/ArrowUpRight";
import { AtIcon } from "@phosphor-icons/react/dist/csr/At";
import { ChartBarIcon } from "@phosphor-icons/react/dist/csr/ChartBar";
import { SquaresFourIcon } from "@phosphor-icons/react/dist/csr/SquaresFour";
import { RobotIcon } from "@phosphor-icons/react/dist/csr/Robot";
import { BookOpenIcon } from "@phosphor-icons/react/dist/csr/BookOpen";
import { CubeIcon } from "@phosphor-icons/react/dist/csr/Cube";
import { StackIcon } from "@phosphor-icons/react/dist/csr/Stack";
import { BrainIcon } from "@phosphor-icons/react/dist/csr/Brain";
import { HeadCircuitIcon } from "@phosphor-icons/react/dist/csr/HeadCircuit";
import { BugIcon } from "@phosphor-icons/react/dist/csr/Bug";
import { CheckIcon as PhosphorCheckIcon } from "@phosphor-icons/react/dist/csr/Check";
import { CheckCircleIcon } from "@phosphor-icons/react/dist/csr/CheckCircle";
import { CaretDownIcon } from "@phosphor-icons/react/dist/csr/CaretDown";
import { CaretLeftIcon } from "@phosphor-icons/react/dist/csr/CaretLeft";
import { CaretRightIcon } from "@phosphor-icons/react/dist/csr/CaretRight";
import { CaretUpIcon } from "@phosphor-icons/react/dist/csr/CaretUp";
import { CircleIcon as PhosphorCircleIcon } from "@phosphor-icons/react/dist/csr/Circle";
import { RecordIcon } from "@phosphor-icons/react/dist/csr/Record";
import { DotsThreeCircleIcon } from "@phosphor-icons/react/dist/csr/DotsThreeCircle";
import { QuestionIcon } from "@phosphor-icons/react/dist/csr/Question";
import { FilmSlateIcon } from "@phosphor-icons/react/dist/csr/FilmSlate";
import { ClockIcon } from "@phosphor-icons/react/dist/csr/Clock";
import { ClockCountdownIcon } from "@phosphor-icons/react/dist/csr/ClockCountdown";
import { CodeIcon } from "@phosphor-icons/react/dist/csr/Code";
import { ShippingContainerIcon } from "@phosphor-icons/react/dist/csr/ShippingContainer";
import { CopyIcon } from "@phosphor-icons/react/dist/csr/Copy";
import { ArrowBendUpLeftIcon } from "@phosphor-icons/react/dist/csr/ArrowBendUpLeft";
import { ArrowBendUpRightIcon } from "@phosphor-icons/react/dist/csr/ArrowBendUpRight";
import { DownloadSimpleIcon } from "@phosphor-icons/react/dist/csr/DownloadSimple";
import { DotsThreeIcon } from "@phosphor-icons/react/dist/csr/DotsThree";
import { EraserIcon } from "@phosphor-icons/react/dist/csr/Eraser";
import { ArrowSquareOutIcon } from "@phosphor-icons/react/dist/csr/ArrowSquareOut";
import { EyeIcon } from "@phosphor-icons/react/dist/csr/Eye";
import { EyeSlashIcon } from "@phosphor-icons/react/dist/csr/EyeSlash";
import { FileIcon as PhosphorFileIcon } from "@phosphor-icons/react/dist/csr/File";
import { FileCodeIcon as PhosphorFileCodeIcon } from "@phosphor-icons/react/dist/csr/FileCode";
import { FileImageIcon } from "@phosphor-icons/react/dist/csr/FileImage";
import { FilePlusIcon as PhosphorFilePlusIcon } from "@phosphor-icons/react/dist/csr/FilePlus";
import { FileTextIcon as PhosphorFileTextIcon } from "@phosphor-icons/react/dist/csr/FileText";
import { FunnelIcon } from "@phosphor-icons/react/dist/csr/Funnel";
import { FlagIcon } from "@phosphor-icons/react/dist/csr/Flag";
import { FolderIcon as PhosphorFolderIcon } from "@phosphor-icons/react/dist/csr/Folder";
import { FolderOpenIcon as PhosphorFolderOpenIcon } from "@phosphor-icons/react/dist/csr/FolderOpen";
import { FolderPlusIcon as PhosphorFolderPlusIcon } from "@phosphor-icons/react/dist/csr/FolderPlus";
import { TreeStructureIcon } from "@phosphor-icons/react/dist/csr/TreeStructure";
import { FolderMinusIcon } from "@phosphor-icons/react/dist/csr/FolderMinus";
import { GaugeIcon as PhosphorGaugeIcon } from "@phosphor-icons/react/dist/csr/Gauge";
import { GitBranchIcon as PhosphorGitBranchIcon } from "@phosphor-icons/react/dist/csr/GitBranch";
import { GitCommitIcon } from "@phosphor-icons/react/dist/csr/GitCommit";
import { GitForkIcon as PhosphorGitForkIcon } from "@phosphor-icons/react/dist/csr/GitFork";
import { GitMergeIcon as PhosphorGitMergeIcon } from "@phosphor-icons/react/dist/csr/GitMerge";
import { GitPullRequestIcon as PhosphorGitPullRequestIcon } from "@phosphor-icons/react/dist/csr/GitPullRequest";
import { GlobeIcon as PhosphorGlobeIcon } from "@phosphor-icons/react/dist/csr/Globe";
import { GlobeSimpleIcon } from "@phosphor-icons/react/dist/csr/GlobeSimple";
import { DotsSixVerticalIcon } from "@phosphor-icons/react/dist/csr/DotsSixVertical";
import { HashIcon as PhosphorHashIcon } from "@phosphor-icons/react/dist/csr/Hash";
import { ClockCounterClockwiseIcon } from "@phosphor-icons/react/dist/csr/ClockCounterClockwise";
import { ImagesSquareIcon } from "@phosphor-icons/react/dist/csr/ImagesSquare";
import { InfoIcon as PhosphorInfoIcon } from "@phosphor-icons/react/dist/csr/Info";
import { BrowserIcon as PhosphorBrowserIcon } from "@phosphor-icons/react/dist/csr/Browser";
import { KeyboardIcon as PhosphorKeyboardIcon } from "@phosphor-icons/react/dist/csr/Keyboard";
import { LaptopIcon as PhosphorLaptopIcon } from "@phosphor-icons/react/dist/csr/Laptop";
import { ListChecksIcon } from "@phosphor-icons/react/dist/csr/ListChecks";
import { ArrowsCounterClockwiseIcon } from "@phosphor-icons/react/dist/csr/ArrowsCounterClockwise";
import { SpinnerGapIcon } from "@phosphor-icons/react/dist/csr/SpinnerGap";
import { CircleNotchIcon } from "@phosphor-icons/react/dist/csr/CircleNotch";
import { ArticleIcon } from "@phosphor-icons/react/dist/csr/Article";
import { LockIcon as PhosphorLockIcon } from "@phosphor-icons/react/dist/csr/Lock";
import { LockOpenIcon as PhosphorLockOpenIcon } from "@phosphor-icons/react/dist/csr/LockOpen";
import { ArrowsOutSimpleIcon } from "@phosphor-icons/react/dist/csr/ArrowsOutSimple";
import { ChatCircleIcon } from "@phosphor-icons/react/dist/csr/ChatCircle";
import { ChatCircleDotsIcon } from "@phosphor-icons/react/dist/csr/ChatCircleDots";
import { ChatIcon } from "@phosphor-icons/react/dist/csr/Chat";
import { ChatsIcon } from "@phosphor-icons/react/dist/csr/Chats";
import { ChatTextIcon } from "@phosphor-icons/react/dist/csr/ChatText";
import { MicrophoneIcon } from "@phosphor-icons/react/dist/csr/Microphone";
import { ArrowsInSimpleIcon } from "@phosphor-icons/react/dist/csr/ArrowsInSimple";
import { MinusIcon as PhosphorMinusIcon } from "@phosphor-icons/react/dist/csr/Minus";
import { MonitorIcon as PhosphorMonitorIcon } from "@phosphor-icons/react/dist/csr/Monitor";
import { DevicesIcon } from "@phosphor-icons/react/dist/csr/Devices";
import { DeviceMobileIcon } from "@phosphor-icons/react/dist/csr/DeviceMobile";
import { MoonIcon as PhosphorMoonIcon } from "@phosphor-icons/react/dist/csr/Moon";
import { DotsThreeVerticalIcon } from "@phosphor-icons/react/dist/csr/DotsThreeVertical";
import { CursorIcon } from "@phosphor-icons/react/dist/csr/Cursor";
import { PlanetIcon } from "@phosphor-icons/react/dist/csr/Planet";
import { PackageIcon as PhosphorPackageIcon } from "@phosphor-icons/react/dist/csr/Package";
import { PaletteIcon as PhosphorPaletteIcon } from "@phosphor-icons/react/dist/csr/Palette";
import { RowsIcon } from "@phosphor-icons/react/dist/csr/Rows";
import { SidebarIcon } from "@phosphor-icons/react/dist/csr/Sidebar";
import { PauseIcon as PhosphorPauseIcon } from "@phosphor-icons/react/dist/csr/Pause";
import { PawPrintIcon as PhosphorPawPrintIcon } from "@phosphor-icons/react/dist/csr/PawPrint";
import { PenNibIcon } from "@phosphor-icons/react/dist/csr/PenNib";
import { PencilSimpleIcon } from "@phosphor-icons/react/dist/csr/PencilSimple";
import { PushPinIcon } from "@phosphor-icons/react/dist/csr/PushPin";
import { PushPinSlashIcon } from "@phosphor-icons/react/dist/csr/PushPinSlash";
import { PlayIcon as PhosphorPlayIcon } from "@phosphor-icons/react/dist/csr/Play";
import { PlusIcon as PhosphorPlusIcon } from "@phosphor-icons/react/dist/csr/Plus";
import { PowerIcon as PhosphorPowerIcon } from "@phosphor-icons/react/dist/csr/Power";
import { PuzzlePieceIcon } from "@phosphor-icons/react/dist/csr/PuzzlePiece";
import { ArrowsClockwiseIcon } from "@phosphor-icons/react/dist/csr/ArrowsClockwise";
import { ArrowCounterClockwiseIcon } from "@phosphor-icons/react/dist/csr/ArrowCounterClockwise";
import { ArrowClockwiseIcon } from "@phosphor-icons/react/dist/csr/ArrowClockwise";
import { PathIcon } from "@phosphor-icons/react/dist/csr/Path";
import { FloppyDiskIcon } from "@phosphor-icons/react/dist/csr/FloppyDisk";
import { ScanIcon } from "@phosphor-icons/react/dist/csr/Scan";
import { MagnifyingGlassIcon } from "@phosphor-icons/react/dist/csr/MagnifyingGlass";
import { PaperPlaneTiltIcon } from "@phosphor-icons/react/dist/csr/PaperPlaneTilt";
import { DatabaseIcon } from "@phosphor-icons/react/dist/csr/Database";
import { ShareNetworkIcon } from "@phosphor-icons/react/dist/csr/ShareNetwork";
import { GearIcon } from "@phosphor-icons/react/dist/csr/Gear";
import { GearSixIcon } from "@phosphor-icons/react/dist/csr/GearSix";
import { ShieldWarningIcon } from "@phosphor-icons/react/dist/csr/ShieldWarning";
import { ShieldCheckIcon as PhosphorShieldCheckIcon } from "@phosphor-icons/react/dist/csr/ShieldCheck";
import { SlidersHorizontalIcon } from "@phosphor-icons/react/dist/csr/SlidersHorizontal";
import { SparkleIcon } from "@phosphor-icons/react/dist/csr/Sparkle";
import { SquareIcon as PhosphorSquareIcon } from "@phosphor-icons/react/dist/csr/Square";
import { SelectionIcon } from "@phosphor-icons/react/dist/csr/Selection";
import { KanbanIcon } from "@phosphor-icons/react/dist/csr/Kanban";
import { NotePencilIcon } from "@phosphor-icons/react/dist/csr/NotePencil";
import { PlusSquareIcon } from "@phosphor-icons/react/dist/csr/PlusSquare";
import { StarIcon as PhosphorStarIcon } from "@phosphor-icons/react/dist/csr/Star";
import { StorefrontIcon } from "@phosphor-icons/react/dist/csr/Storefront";
import { SunIcon as PhosphorSunIcon } from "@phosphor-icons/react/dist/csr/Sun";
import { TargetIcon as PhosphorTargetIcon } from "@phosphor-icons/react/dist/csr/Target";
import { TerminalIcon as PhosphorTerminalIcon } from "@phosphor-icons/react/dist/csr/Terminal";
import { TicketIcon as PhosphorTicketIcon } from "@phosphor-icons/react/dist/csr/Ticket";
import { TrashIcon } from "@phosphor-icons/react/dist/csr/Trash";
import { UploadSimpleIcon } from "@phosphor-icons/react/dist/csr/UploadSimple";
import { UserCircleIcon } from "@phosphor-icons/react/dist/csr/UserCircle";
import { WrenchIcon as PhosphorWrenchIcon } from "@phosphor-icons/react/dist/csr/Wrench";
import { WebhooksLogoIcon } from "@phosphor-icons/react/dist/csr/WebhooksLogo";
import { XIcon as PhosphorXIcon } from "@phosphor-icons/react/dist/csr/X";
import { XCircleIcon as PhosphorXCircleIcon } from "@phosphor-icons/react/dist/csr/XCircle";
import { LightningIcon } from "@phosphor-icons/react/dist/csr/Lightning";

export type IconProps = Omit<PhosphorIconProps, "strokeWidth">;
export type AppIcon = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;

function createIcon(
  Source: PhosphorIcon,
  displayName: string,
  defaults: Partial<IconProps> = {},
): AppIcon {
  const Component = forwardRef<SVGSVGElement, IconProps>(
    ({ children, color = "currentColor", weight = "regular", ...props }, ref) => {
      // Render-prop primitives may inject a text fallback; glyphs stay atomic like the old adapter.
      void children;
      return <Source ref={ref} color={color} weight={weight} {...defaults} {...props} />;
    },
  );
  Component.displayName = displayName;
  return Component;
}

export const Activity = createIcon(PulseIcon, "Activity");
export const AlertCircle = createIcon(WarningCircleIcon, "AlertCircle");
export const AlertTriangle = createIcon(WarningIcon, "AlertTriangle");
export const Archive = createIcon(ArchiveIcon, "Archive");
export const ArchiveRestore = createIcon(TrayArrowUpIcon, "ArchiveRestore");
export const ArrowDown = createIcon(ArrowDownIcon, "ArrowDown");
export const ArrowLeft = createIcon(ArrowLeftIcon, "ArrowLeft");
export const ArrowRight = createIcon(ArrowRightIcon, "ArrowRight");
export const ArrowUp = createIcon(ArrowUpIcon, "ArrowUp");
export const ArrowUpRight = createIcon(ArrowUpRightIcon, "ArrowUpRight");
export const AtSign = createIcon(AtIcon, "AtSign");
export const BarChart3 = createIcon(ChartBarIcon, "BarChart3");
export const Blocks = createIcon(SquaresFourIcon, "Blocks");
export const Bot = createIcon(RobotIcon, "Bot");
export const BookOpen = createIcon(BookOpenIcon, "BookOpen");
export const Box = createIcon(CubeIcon, "Box");
export const Boxes = createIcon(StackIcon, "Boxes");
export const Brain = createIcon(BrainIcon, "Brain");
export const BrainCircuit = createIcon(HeadCircuitIcon, "BrainCircuit");
export const Bug = createIcon(BugIcon, "Bug");
export const CalendarClock = createIcon(ClockCountdownIcon, "CalendarClock");
export const ChartNoAxesColumn = createIcon(ChartBarIcon, "ChartNoAxesColumn");
export const Check = createIcon(PhosphorCheckIcon, "Check");
export const CheckCircle2 = createIcon(CheckCircleIcon, "CheckCircle2");
export const CheckIcon = createIcon(PhosphorCheckIcon, "CheckIcon");
export const ChevronDown = createIcon(CaretDownIcon, "ChevronDown");
export const ChevronDownIcon = createIcon(CaretDownIcon, "ChevronDownIcon");
export const ChevronLeft = createIcon(CaretLeftIcon, "ChevronLeft");
export const ChevronRight = createIcon(CaretRightIcon, "ChevronRight");
export const ChevronUp = createIcon(CaretUpIcon, "ChevronUp");
export const ChevronUpIcon = createIcon(CaretUpIcon, "ChevronUpIcon");
export const Circle = createIcon(PhosphorCircleIcon, "Circle");
export const CircleAlert = createIcon(WarningCircleIcon, "CircleAlert");
export const CircleCheck = createIcon(CheckCircleIcon, "CircleCheck");
export const CircleDot = createIcon(RecordIcon, "CircleDot");
export const CircleEllipsis = createIcon(DotsThreeCircleIcon, "CircleEllipsis");
export const CircleHelp = createIcon(QuestionIcon, "CircleHelp");
export const Clapperboard = createIcon(FilmSlateIcon, "Clapperboard");
export const Clock3 = createIcon(ClockIcon, "Clock3");
export const Code2 = createIcon(CodeIcon, "Code2");
export const Container = createIcon(ShippingContainerIcon, "Container");
export const Copy = createIcon(CopyIcon, "Copy");
export const CornerUpLeft = createIcon(ArrowBendUpLeftIcon, "CornerUpLeft");
export const CornerUpRight = createIcon(ArrowBendUpRightIcon, "CornerUpRight");
export const Download = createIcon(DownloadSimpleIcon, "Download");
export const Ellipsis = createIcon(DotsThreeIcon, "Ellipsis");
export const Eraser = createIcon(EraserIcon, "Eraser");
export const ExternalLink = createIcon(ArrowSquareOutIcon, "ExternalLink");
export const Eye = createIcon(EyeIcon, "Eye");
export const EyeOff = createIcon(EyeSlashIcon, "EyeOff");
export const File = createIcon(PhosphorFileIcon, "File");
export const FileClock = createIcon(ClockCounterClockwiseIcon, "FileClock");
export const FileCode = createIcon(PhosphorFileCodeIcon, "FileCode");
export const FileCode2 = createIcon(PhosphorFileCodeIcon, "FileCode2");
export const FileImage = createIcon(FileImageIcon, "FileImage");
export const FileJson = createIcon(PhosphorFileCodeIcon, "FileJson");
export const FilePlus = createIcon(PhosphorFilePlusIcon, "FilePlus");
export const FileText = createIcon(PhosphorFileTextIcon, "FileText");
export const FileType = createIcon(PhosphorFileTextIcon, "FileType");
export const Filter = createIcon(FunnelIcon, "Filter");
export const Flag = createIcon(FlagIcon, "Flag");
export const Folder = createIcon(PhosphorFolderIcon, "Folder");
export const FolderDown = createIcon(TrayArrowDownIcon, "FolderDown");
export const FolderOpen = createIcon(PhosphorFolderOpenIcon, "FolderOpen");
export const FolderPlus = createIcon(PhosphorFolderPlusIcon, "FolderPlus");
export const FolderTree = createIcon(TreeStructureIcon, "FolderTree");
export const FolderX = createIcon(FolderMinusIcon, "FolderX");
export const Gauge = createIcon(PhosphorGaugeIcon, "Gauge");
export const GitBranch = createIcon(PhosphorGitBranchIcon, "GitBranch");
export const GitCommitHorizontal = createIcon(GitCommitIcon, "GitCommitHorizontal");
export const GitFork = createIcon(PhosphorGitForkIcon, "GitFork");
export const GitMerge = createIcon(PhosphorGitMergeIcon, "GitMerge");
export const GitPullRequest = createIcon(PhosphorGitPullRequestIcon, "GitPullRequest");
export const Globe = createIcon(PhosphorGlobeIcon, "Globe");
export const Globe2 = createIcon(GlobeSimpleIcon, "Globe2");
export const GripVertical = createIcon(DotsSixVerticalIcon, "GripVertical");
export const Hash = createIcon(PhosphorHashIcon, "Hash");
export const History = createIcon(ClockCounterClockwiseIcon, "History");
export const ImagePlus = createIcon(ImagesSquareIcon, "ImagePlus");
export const Info = createIcon(PhosphorInfoIcon, "Info");
export const Inspect = createIcon(PhosphorBrowserIcon, "Inspect");
export const Keyboard = createIcon(PhosphorKeyboardIcon, "Keyboard");
export const Laptop = createIcon(PhosphorLaptopIcon, "Laptop");
export const ListChecks = createIcon(ListChecksIcon, "ListChecks");
export const ListRestart = createIcon(ArrowsCounterClockwiseIcon, "ListRestart");
export const ListTodo = createIcon(ListChecksIcon, "ListTodo");
export const Loader2 = createIcon(SpinnerGapIcon, "Loader2");
export const LoaderCircle = createIcon(CircleNotchIcon, "LoaderCircle");
export const Logs = createIcon(ArticleIcon, "Logs");
export const Lock = createIcon(PhosphorLockIcon, "Lock");
export const LockOpen = createIcon(PhosphorLockOpenIcon, "LockOpen");
export const Maximize2 = createIcon(ArrowsOutSimpleIcon, "Maximize2");
export const MessageCircle = createIcon(ChatCircleIcon, "MessageCircle");
export const MessageCircleQuestion = createIcon(ChatCircleDotsIcon, "MessageCircleQuestion");
export const MessageSquare = createIcon(ChatIcon, "MessageSquare");
export const MessageSquarePlus = createIcon(ChatsIcon, "MessageSquarePlus");
export const MessageSquareText = createIcon(ChatTextIcon, "MessageSquareText");
export const Mic = createIcon(MicrophoneIcon, "Mic");
export const Minimize2 = createIcon(ArrowsInSimpleIcon, "Minimize2");
export const Minus = createIcon(PhosphorMinusIcon, "Minus");
export const Monitor = createIcon(PhosphorMonitorIcon, "Monitor");
export const MonitorCog = createIcon(GearSixIcon, "MonitorCog");
export const MonitorSmartphone = createIcon(DevicesIcon, "MonitorSmartphone");
export const Smartphone = createIcon(DeviceMobileIcon, "Smartphone");
export const Moon = createIcon(PhosphorMoonIcon, "Moon");
export const MoreHorizontal = createIcon(DotsThreeIcon, "MoreHorizontal");
export const MoreVertical = createIcon(DotsThreeVerticalIcon, "MoreVertical");
export const MousePointer2 = createIcon(CursorIcon, "MousePointer2");
export const Orbit = createIcon(PlanetIcon, "Orbit");
export const Package = createIcon(PhosphorPackageIcon, "Package");
export const PackageCheck = createIcon(PhosphorShieldCheckIcon, "PackageCheck");
export const PackagePlus = createIcon(DownloadSimpleIcon, "PackagePlus");
export const Palette = createIcon(PhosphorPaletteIcon, "Palette");
export const PanelBottom = createIcon(RowsIcon, "PanelBottom");
export const PanelLeft = createIcon(SidebarIcon, "PanelLeft");
export const PanelRight = createIcon(SidebarIcon, "PanelRight", { mirrored: true });
export const Pause = createIcon(PhosphorPauseIcon, "Pause");
export const PawPrint = createIcon(PhosphorPawPrintIcon, "PawPrint");
export const PenLine = createIcon(PenNibIcon, "PenLine");
export const Pencil = createIcon(PencilSimpleIcon, "Pencil");
export const Pin = createIcon(PushPinIcon, "Pin");
export const PinOff = createIcon(PushPinSlashIcon, "PinOff");
export const Play = createIcon(PhosphorPlayIcon, "Play");
export const Plus = createIcon(PhosphorPlusIcon, "Plus");
export const Power = createIcon(PhosphorPowerIcon, "Power");
export const Puzzle = createIcon(PuzzlePieceIcon, "Puzzle");
export const RefreshCw = createIcon(ArrowsClockwiseIcon, "RefreshCw");
export const RotateCcw = createIcon(ArrowCounterClockwiseIcon, "RotateCcw");
export const RotateCw = createIcon(ArrowClockwiseIcon, "RotateCw");
export const Route = createIcon(PathIcon, "Route");
export const Save = createIcon(FloppyDiskIcon, "Save");
export const ScanText = createIcon(ScanIcon, "ScanText");
export const Search = createIcon(MagnifyingGlassIcon, "Search");
export const SearchIcon = createIcon(MagnifyingGlassIcon, "SearchIcon");
export const Send = createIcon(PaperPlaneTiltIcon, "Send");
export const Server = createIcon(DatabaseIcon, "Server");
export const Share2 = createIcon(ShareNetworkIcon, "Share2");
export const Settings = createIcon(GearIcon, "Settings");
export const Settings2 = createIcon(GearSixIcon, "Settings2");
export const ShieldAlert = createIcon(ShieldWarningIcon, "ShieldAlert");
export const ShieldCheck = createIcon(PhosphorShieldCheckIcon, "ShieldCheck");
export const SlidersHorizontal = createIcon(SlidersHorizontalIcon, "SlidersHorizontal");
export const Sparkles = createIcon(SparkleIcon, "Sparkles");
export const Square = createIcon(PhosphorSquareIcon, "Square");
export const SquareDashedMousePointer = createIcon(SelectionIcon, "SquareDashedMousePointer");
export const SquareKanban = createIcon(KanbanIcon, "SquareKanban");
export const SquarePen = createIcon(NotePencilIcon, "SquarePen");
export const SquarePlus = createIcon(PlusSquareIcon, "SquarePlus");
export const Star = createIcon(PhosphorStarIcon, "Star");
export const Store = createIcon(StorefrontIcon, "Store");
export const Sun = createIcon(PhosphorSunIcon, "Sun");
export const Target = createIcon(PhosphorTargetIcon, "Target");
export const Terminal = createIcon(PhosphorTerminalIcon, "Terminal");
export const TerminalIcon = createIcon(PhosphorTerminalIcon, "TerminalIcon");
export const Ticket = createIcon(PhosphorTicketIcon, "Ticket");
export const Trash2 = createIcon(TrashIcon, "Trash2");
export const TriangleAlert = createIcon(WarningIcon, "TriangleAlert");
export const Upload = createIcon(UploadSimpleIcon, "Upload");
export const UserRound = createIcon(UserCircleIcon, "UserRound");
export const Wrench = createIcon(PhosphorWrenchIcon, "Wrench");
export const Webhook = createIcon(WebhooksLogoIcon, "Webhook");
export const X = createIcon(PhosphorXIcon, "X");
export const XCircle = createIcon(PhosphorXCircleIcon, "XCircle");
export const XIcon = createIcon(PhosphorXIcon, "XIcon");
export const Zap = createIcon(LightningIcon, "Zap");
